<?php
    $product = $block->getCurrentProduct();
    $productid = $product->getId();
    $_productStock = $block->getProductStock($productid);
?>
<?php if ($block->isEnable() && $block->isAllowCustomerGroup() == 1):?>
    <?php if ($product->getTypeId() == "simple"):?>
        <?php if ($product->getIsEnableOutofstock()==1):?>
            <?php if (!$product->isSalable()):?>
        <div class="mageants-notify-main">
            <div id="mageants-notify-form">
                <form  id= "notify" action="<?= /* @noEscape */ $block->getSaveUrl(); ?>" method = "POST">
                    <div>
                        <p><?= /* @noEscape */ $block->getNotificationMessage(); ?></p>
                        <input type="hidden" name="customerId"
                        value="<?= /* @noEscape */ $block->getLoggedCustomerId(); ?>">
                        <input type="hidden" name="productSku"
                        value="<?= /* @noEscape */ $product->getSku(); ?>">
                        <input type="hidden" name="productName"
                        value="<?= /* @noEscape */ $product->getName(); ?>">
                        <input type="hidden" name="producturl" class="producturl"
                        value="<?= /* @noEscape */ $product->getUrlKey(); ?>">
                    </div>
                    <div>
                        <div>
                            <input type="email" name="notify"
                            placeholder="<?= $block->escapeHtml('Please enter your email id') ?>"
                            value = "<?php if ($block->isLoggedIn()) {//@codingStandardsIgnoreStart
                                echo trim($block->getLoggedCustomerEmail()); } //@codingStandardsIgnoreEnd ?>">
                        </div>
                        <div style="margin-top: 10px;">
                            <button class="action primary" formaction="<?= /* @noEscape */ $block->getSaveUrl(); ?>"
                                type="submit"
                                title="<?= $block->escapeHtml('Notify') ?>"><?= $block->escapeHtml('Notify') ?>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <?php endif;?>
        <?php endif;?>
    <?php endif;?>
    <?php if ($product->getIsEnableOutofstock()==1):?>
        <?php if ($product->getTypeId() == "configurable" && !$_productStock->getIsInStock()):?>
        <div class="mageants-notify-main">
            <div id="mageants-notify-form">
                <form  id= "notify" action="<?= /* @noEscape */ $block->getSaveUrl(); ?>" method = "POST">
                    <div>
                        <p><?= /* @noEscape */ $block->getNotificationMessage(); ?></p>
                        <input type="hidden" name="customerId"
                        value="<?= /* @noEscape */ $block->getLoggedCustomerId(); ?>">
                        <input type="hidden" name="productSku" value="<?= /* @noEscape */ $product->getSku(); ?>">
                        <input type="hidden" name="productName" value="<?= /* @noEscape */ $product->getName(); ?>">
                        <input type="hidden" name="producturl" class="producturl"
                        value="<?= /* @noEscape */ $product->getUrlKey(); ?>">
                    </div>
                    <div>
                        <div>
                            <input type="email" name="notify"
                            placeholder="<?= $block->escapeHtml('Please enter your email id') ?>"
                            value = "<?php if ($block->isLoggedIn()) {//@codingStandardsIgnoreStart
                                echo trim($block->getLoggedCustomerEmail()); } //@codingStandardsIgnoreEnd ?>">
                        </div>
                        <div style="margin-top: 10px;">
                            <button class="action primary" formaction="<?= /* @noEscape */ $block->getSaveUrl(); ?>"
                                type="submit"
                                title="<?= $block->escapeHtml('Notify') ?>"><?= $block->escapeHtml('Notify') ?></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <?php endif;?>
    <?php endif;?>

    <?php if ($block->isEnable() && $product->getTypeId() == "configurable"):?>
        <div class="mageants-notify-main">
            <div id="mageants-notify-form-simple">
                <?php
                $product = $block->getCurrentProduct();
                $data = $product->getTypeInstance()->getConfigurableOptions($product);
                $optionsData = $product->getTypeInstance(true)->getConfigurableAttributesAsArray($product);
                $superAttrCode=[];
                foreach ($optionsData as $option) {
                    $superAttrCode[]=$option['attribute_code'];
                }
                $usedProducts = $product->getTypeInstance()->getUsedProductCollection($product);
                foreach ($usedProducts as $childProduct) {
                    $stockProduct = $block->getProductStock($childProduct->getId());
                    
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $simpleProduct = $block->getProduct($childProduct->getId());
                        $id = "";
                    foreach ($superAttrCode as $key => $value) {
                            $id = $id.$simpleProduct->getData($value);
                    }
                    if (!$simpleProduct->isSalable() && $simpleProduct->getIsEnableOutofstock() == 1) {
                        ?>    
                        <form  id= "<?= /* @noEscape */ $id; ?>" action="<?= /* @noEscape */ $block->getSaveUrl(); ?>"
                            method = "POST" style="display: none;">
                            <div>
                                <p><?= /* @noEscape */ $block->getNotificationMessage(); ?></p>
                                <input type="hidden" name="customerId"
                                value="<?= /* @noEscape */ $block->getLoggedCustomerId(); ?>">
                                <input type="hidden" name="productSku"
                                value="<?= /* @noEscape */ $simpleProduct->getSku(); ?>">
                                <input type="hidden" name="productName"
                                value="<?= /* @noEscape */ $simpleProduct->getName(); ?>">
                                <input type="hidden" name="producturl" class="producturl"
                                value="<?= /* @noEscape */ $product->getUrlKey(); ?>">
                            </div>
                            <div>
                                <div>
                                    <input type="email" name="notify"
                                    placeholder="<?= $block->escapeHtml('Please enter your email id') ?>"
                                    value = "<?php if ($block->isLoggedIn()) { //@codingStandardsIgnoreStart
                                        echo trim($block->getLoggedCustomerEmail()); } //@codingStandardsIgnoreEnd ?>">
                                </div>
                                <div style="margin-top: 10px;">
                                    <button class="action primary"
                                    type="submit"
                                    title="<?= $block->escapeHtml('Notify') ?>"><?= $block->escapeHtml('Notify') ?>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <?php
                    }
                }
                ?>
            </div>
        </div>
    <?php endif;?>
<?php endif;?>

<script type="text/javascript">
    require([
      'jquery',
      'jquery/ui'
    ], function($){
         $(document).ready(function() {
           $('.swatch-opt').on('click', '.swatch-option', function () {
                setTimeout(function(){
                    OnClick();
                },100);
                
            });
            //start when configrable product outofstock
            
                  getstockstatus = '<?= /* @noEscape */ $_productStock->getIsInStock() ;?>';
                  if(getstockstatus==0){
                      jQuery('.product-options-wrapper').css("display", "none");
                      jQuery('.product-add-form .product-options-bottom .box-tocart ').css("display", "none");
                      jQuery('.product-info-stock-sku span').html('Out Of stock');
                  }
               
              //End when configrable product outofstock

            $('.swatch-opt').on('change', '.swatch-select', function () {
                 setTimeout(function(){
                    OnClick();
                },100);
            });

            $('#product-options-wrapper select').on('change', function () {
                var finalval = "";
                jQuery('#product-options-wrapper select').each(function() {
                    var selectedVal = $(this).val();
                    if (selectedVal != "") 
                    {
                        finalval = finalval+selectedVal;
                    }
                    jQuery('.mageants-notify-main #mageants-notify-form-simple > form').each(function() {
                        var id = jQuery(this).attr('id');
                           if (id == finalval) 
                           {
                               $(this).css("display", "block");
                           }
                           else{
                               $(this).css("display", "none");
                           }
                    });                    
                });
            });    

        });
        function OnClick () 
        {            
            var super_attribute = [];
            jQuery('.swatch-attribute').each(function() {
                
                var id = jQuery(this).attr('data-attribute-id');
                
                if(id == undefined){
                    var id = jQuery(this).attr('attribute-id');
                }
                
                var value = jQuery(this).attr('data-option-selected');
                
                if(value == undefined){
                    var value = jQuery(this).attr('option-selected');
                }

                if (value != "") 
                {
                    super_attribute[id] = value;
                }
            });
            // alert(super_attribute);
            var attr_key = Array();
            var attr_value = Array();
            var i = 0;
            $.each(super_attribute, function( index, value ) {
                if (value != undefined) {
                    attr_key[i] = index;
                    attr_value[i] = value;
                    i = i + 1;
                }                
            });

            var final = "";
            for (var i = attr_value.length - 1; i >= 0 ; i--) {
                  final = final+attr_value[i];
            }
            var isOutOfStock = 0;
            jQuery('.mageants-notify-main #mageants-notify-form-simple > form').each(function() {
                var id = jQuery(this).attr('id');
                   if (id == final) 
                   {
                       $(this).css("display", "block");
                       $('.product-info-stock-sku span').html('Out Of Stock');
                       isOutOfStock = 1;
                   }
                   else{
                       $(this).css("display", "none");
                       $('.product-info-stock-sku span').html('In stock');
                   }
            });
            if (isOutOfStock == 1) {
                jQuery('.product-add-form .product-options-bottom .box-tocart').css("display", "none");
            }
            else{
                jQuery('.product-add-form .product-options-bottom .box-tocart').css("display", "block");
            }
        }

    }); 
</script>
