<?php $subscribedProduct = $block->getSubscribedProductSku();
                    
if (empty($subscribedProduct)) {?>
    <div class="message info empty">
        <span>
            <?= $block->escapeHtml('You have not added any products for Subscription yet.') ?>
        </span></div>
<?php }?>
<div>
    <div class="products wrapper list products-list">
        <form id="notify-product-list-form" method="POST">
            <input type="hidden" name="customer_id" value="<?= /* @noEscape */  $block->getLoggedCustomerId(); ?>">
            <ol class="products list items product-items">
                <?php
                    
                foreach ($subscribedProduct as $key => $value) {
                    $sku = $value['sku'];
                     $product = $block->getProduct($sku);
                    if ($product == false) {
                           continue;
                    }
                     $mediaUrl = $block->getMediaUrl();
                     $imageUrl = $mediaUrl."catalog/product".$product->getImage();
                     $_productStock = $block->getStockItem($product->getId());
                    if ($_productStock == false) {
                            continue;
                    }
                        
                    ?>
                         <li class="item product product-item">
                             <div class="product-item-info">
                                 <div class="product photo product-item-photo">
                                     <img class="mageants-product-image-photo"
                                     src="<?= /* @noEscape */ $imageUrl; ?>" width="240" height="300">
                                 </div>
                                 <div class="product details product-item-details">
                                     <div class="mageants-product-item-details">
                                         <span class="product-item-name"> <?= /* @noEscape */ $value['name']; ?></span>
                                     </div>
                                     <div class="mageants-product-item-details">
                                         <span class="product-item-email">
                                            <?= /* @noEscape */ $value['email']; ?></span>
                                     </div>
                                     <div class="mageants-product-item-details">
                                         <span class="product-item-status">
                                            <?php if ($_productStock->getIsInStock()) {
                                                echo "In Stock";
                                            } else { echo "Out of Stock"; } ?></span>
                                     </div>
                                     <div class="mageants-notify-button">
                                         <button class="action primary"
                                         formaction="<?= /* @noEscape */ $block->getStopNotifyAction()."/sku/".$sku; ?>"
                                         type="submit" id="stop-notify">
                                         <?php
                                            if ($value['notify_status'] == 1) { echo "Stop Notify";
                                            } else { echo "Start Notify";}?></button>
                                         <button class="action primary" type="submit" id="remove-notify"
                                         formaction="<?= /* @noEscape */ $block->getStopRemoveAction()."/sku/".$sku; ?>"
                                         >
                                        Remove</button>
                                     </div>
                                 </div>                             
                             </div>
                         </li>
                         <?php
                }
                ?>
            </ol>
        </form>
    </div>
</div>
<style type="text/css">
    .mageants-product-image-photo{
        bottom: 0;
        display: block;
        left: 0;
        margin: auto;
        max-width: 100%;
        position: relative;
        right: 0;
        top: 0;
        max-width: inherit;
        height: 250px;
    }
</style>