<?php
/**
 * @category Mageants MaintenanceMode
 * @package Mageants_MaintenanceMode
 * @copyright Copyright (c) 2019 Mageants
 * @author Mageants Team <support@mageants.com>
 */

/**
 * @var \Mageants\MaintenanceMode\Block\Preview\Background $block ;
 */
$data = $block->getFormData();
?>

<div id="mageants-background">
    <!--Multiple Image Background-->
    <?php if ($block->getBgType() === 'multiple_images') : ?>
        <?php $listImagesUrl = $block->getListImagesUrls(); ?>
        <style>
            .maintenancemode-preview-<?= /* @noEscape */ $block->getPage() ?> {
                background: no-repeat center center fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
                transition-delay: 2s;
            }
        </style>
        <script>
            require([
                'jquery'
            ], function ($) {
                var images    = '<?= /* @noEscape */ $listImagesUrl ?>';
                images        = images.split(',');
                var nextImage = 0;
                doSlideShow();

                function doSlideShow () {
                    if (nextImage >= images.length) {
                        nextImage = 0;
                    }
                    $('.maintenancemode-preview-<?= /* @noEscape */ $block->getPage() ?>')
                    .fadeIn('slow', function () {
                        setTimeout(doSlideShow, 5000);
                    }).css('background-image', 'url("' + images[nextImage++] + '")');
                }
            });
        </script>
    <?php endif; ?>

    <!--Single Image Background-->
    <?php if ($block->getBgType() === 'image') : ?>
        <style>
            .maintenancemode-preview-<?= /* @noEscape */ $block->getPage() ?> {
                background: url("<?= /* @noEscape */ $block->getImageBg() ?>") no-repeat center center fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
            }
        </style>
    <?php endif; ?>

    <!--Video Background-->
    <?php if (array_key_exists($block->getVideoCode(), $data)
        && $block->getBgType() === 'video'
        && $block->getVideoUrl($data[$block->getVideoCode()])) : ?>
        <video autoplay muted loop id="mageants-video">
            <source src="<?= $block->escapeHtmlAttr($block->getVideoUrl($data[$block->getVideoCode()])) ?>"
                    type="video/mp4">
        </video>
    <?php endif; ?>
</div>
