<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

$numberBarcodeExist = $block->getNumberBarCodeExist();
$numberSkuExist = $block->getNumberSkuExist();
if (!$numberBarcodeExist) {
    $numberBarcodeExist = 0;
}
if (!$numberSkuExist) {
    $numberSkuExist = 0;
}
?>
<?php if ($block->isHasError()) :?>
<div class="messages">
    <div class="message message-error message-in-rating-edit">
        <div>
            <b><?php /* @escapeNotVerified */echo __('Invalid data'); ?></b>
        </div>
        <div>
            <?php /* @escapeNotVerified */
                if ($numberBarcodeExist && $numberSkuExist) {
                    echo __(
                        'There are %1 barcodes existed and there are %2 invalid skus. You must download', 
                        $numberBarcodeExist, 
                        $numberSkuExist
                    );
                } elseif ($numberBarcodeExist) {
                    echo __('There are %1 barcodes existed. You must download', $numberBarcodeExist);
                } elseif ($numberSkuExist){
                    echo __('There are %1 invalid skus. You must download', $numberSkuExist);
                }
                if($numberBarcodeExist || $numberSkuExist){
                    ?>
                    <a href="<?php echo $block->getUrl('barcodesuccess/index/downloadinvalidcsv')?>">
                        <?php echo __('this file');?>
                    </a>
                    <?php echo __(' to modify and try to import them again.'); 
                }
            ?>
        </div>
    </div>
</div>
<?php endif;?>
