<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var \Magestore\Stocktaking\Block\Adminhtml\Stocktaking\Import\NoticeMessage $block*/
?>
<?php if ($block->isHasError()):?>
    <div class="messages">
        <div class="message message-error message-in-rating-edit">
            <div>
                <b><?= /* @noEscape */ __('Invalid data'); ?></b>
            </div>
            <div>
                <?= /* @noEscape */
                    __('Some products could not be imported. Please download ');
                ?>
                <a href="<?= /* @noEscape */ $block->getInvalidFileCsvUrl();?>">
                    <?= /* @noEscape */ __('this file');?></a>
                <?= /* @noEscape */ __(' for more detail'); ?>
            </div>
        </div>
    </div>
<?php endif;?>
