<?php
/**
 *  Copyright © Magestore. All rights reserved.
 *  See COPYING.txt for license details.
 */
/* @var $block \Magestore\ReportSuccess\Block\Adminhtml\Report\Panel\AbstractReportPanel */ ?>
<?php if ($block->isVisible()): ?>
    <div class="panel panel-default">
        <div class="panel-heading"><?= /* @noEscape */ __($block->getHeadingTitle()) ?></div>
        <div class="panel-body">
            <div class="row">
                <?php /** @var \Magestore\ReportSuccess\Api\Data\ReportPanelItemInterface $panelItem */
                foreach ($block->getPanelItemVisible() as $panelItemId => $panelItem): ?>
                    <?php if ($panelItem->getIsVisible()): ?>
                        <?php $reportLink = $block->getActionUrl($panelItem->getAction()) ?>
                        <div class="col-sm-3">
                            <div class="item-staff">
                                <div class="actions">
                                    <a href="<?= /* @noEscape */ $reportLink ?>">
                                        <span class="<?= /* @noEscape */ 'icon-icon-Back-end-omc-report-'
                                        . $panelItem->getId() ?>"></span>
                                    </a>
                                    <div class="details">
                                        <a href="<?= /* @noEscape */ $reportLink ?>">
                                            <label><?= /* @noEscape */ __($panelItem->getTitle()); ?></label>
                                        </a>
                                        <p><?= /* @noEscape */ __($panelItem->getDescription()); ?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach ?>
            </div>
        </div>
    </div>
<?php endif; ?>