<?php
/**
 * @category Mageants Richsnippets
 * @package Mageants_Richsnippets
 * @copyright Copyright (c) 2019 Mageants
 * @author Mageants Team <support@mageants.com>
 */

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$blockobj = $this->getLayout()->createBlock("Mageants\Richsnippets\Block\Richsnippets");
$counter = 1 ;
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else : ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) : ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()) : ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else : ?>
                                        <?php if ($_product->isAvailable()) : ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else : ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription) :?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
<?php
    $brand_name = $_product->getResource()->getAttribute($blockobj->getConfigrations()->getBrandName())->getFrontend()->getValue($_product);
    $mpn = $_product->getResource()->getAttribute($blockobj->getConfigrations()->getManufacturer())->getFrontend()->getValue($_product);
    $_ratingSummary = $blockobj->getRatingSummary($_product);
    $_reviewCount = $blockobj->getTotalReviews($_product);
    $currencysymbol = $blockobj->getCurrencySymbol();
    $currencycode = $blockobj->getCurrencyCode();
    $productdescription = $blockobj->getCategoryPropductDescription($_product->getId());
    $specialprice = $_product->getSpecialPrice();
    $specialtodate = $_product->getSpecialToDate();
?>
<meta name="keywords" content="<?php echo $_product->getName(); ?>" />
<script type="application/ld+json">
    {
      "@context": "https://schema.org/",
      "@type": "Product",
      "name": "<?php echo $_product->getName(); ?>",
      "image": [
        "<?php echo $this->getUrl()."pub/media/catalog/product".$_product->getImage(); ?>"
       ],
      "description": "<?php echo $productdescription; ?>",
      "sku": "<?php echo $_product->getSku(); ?>",
      "mpn": "<?php echo $mpn; ?>",
        <?php if ($blockobj->getConfigrations()->isProductRichDataEnable()) : ?>
            "brand": {
               "@type": "Thing",
               "name": "<?php echo $brand_name; ?>"
            },
        <?php endif; ?>
        <?php if ($_ratingSummary) { ?>
        <?php if ($blockobj->getConfigrations()->isProductRichDataEnable()) : ?>
        <?php if ($blockobj->getConfigrations()->getRatingStatus()) : ?> 
            "review": {
                "@type": "Review",
                "reviewRating": {
                  "@type": "Rating",
                  "ratingValue": <?php
                                $rating = number_format((($_ratingSummary * 5)/100), 1);
                                echo __(floatval($rating)); ?>,
                  "bestRating": "5"
                },
                "author": {
                  "@type": "Person",
                  "name": "<?php echo $_product->getName(); ?>"
                }
              },
        <?php endif; ?>
        <?php endif; ?>
    <?php if ($blockobj->getConfigrations()->isProductRichDataEnable()) : ?>
        <?php if ($blockobj->getConfigrations()->getRatingStatus()) : ?> 
              "aggregateRating": {
                "@type": "AggregateRating",
                "ratingValue": <?php
                                $rating = number_format((($_ratingSummary * 5)/100), 1);
                                echo __(floatval($rating)); ?>,
                "reviewCount": <?php echo __($_reviewCount); ?>
              },
        <?php endif; ?>
    <?php endif; ?>
        <?php } ?>
        "offers": [[],
        <?php if (($_product->getTypeId() == "grouped")) {
                $productTypeInstance = $_product->getTypeInstance();
                $usedProducts = $productTypeInstance->getAssociatedProducts($_product);
                $gettotalproduct = count($usedProducts);
                $incrementer = 1;
            foreach ($usedProducts as $child) :
                $specialprice = $child->getFinalPrice();
                $specialtodate = $child->getSpecialToDate();
        ?>
        <?php if ($incrementer != $gettotalproduct) { ?>
        {
            "@type": "Offer",
            "url": "<?php echo $this->getUrl(); ?>",
            "priceCurrency": "<?php echo $currencycode ; ?>",
            <?php if (!empty($specialprice)) { ?>
                "price":  <?php echo __(number_format((float)$child->getFinalPrice(), 2, '.', '')); ?>,   
                "priceValidUntil": "<?php echo $specialtodate ; ?>",
            <?php } else { ?>
            "price":  <?php echo __(number_format((float)$child->getFinalPrice(), 2, '.', '')); ?>,
            <?php } ?>
            <?php if ($blockobj->getConfigrations()->isProductRichDataEnable()) : ?>
            <?php if ($blockobj->getConfigrations()->getShowConditionStatus()) : ?> 
                "itemCondition": "https://schema.org/NewCondition",
            <?php endif; ?>
            <?php endif; ?>
            <?php if ($blockobj->getConfigrations()->isProductRichDataEnable()) : ?>
            <?php if ($blockobj->getConfigrations()->getProductAvaiblityStatus()) : ?>    
                <?php if ($_product->isAvailable()) : ?>
                    "availability": "https://schema.org/InStock"
                <?php else : ?>
                    "availability": "https://schema.org/OutStock"
                <?php endif; ?>
            <?php endif; ?>
            <?php endif; ?>
            ,"seller": {
                "@type": "Organization",
                "name": "Executive Objects"
             }
        },
        <?php $incrementer++; ?>
        <?php } else { ?>
            {
                "@type": "Offer",
                "url": "<?php echo $this->getUrl(); ?>",
                "priceCurrency": "<?php echo $currencycode ; ?>",
                <?php if (!empty($specialprice)) { ?>
                    "price":  <?php echo __(number_format((float)$child->getFinalPrice(), 2, '.', '')); ?>,   
                    "priceValidUntil": "<?php echo $specialtodate ; ?>",
                <?php } else { ?>
                "price":  <?php echo __(number_format((float)$child->getFinalPrice(), 2, '.', '')); ?>,
                <?php } ?>
                <?php if ($blockobj->getConfigrations()->isProductRichDataEnable()) : ?>
                <?php if ($blockobj->getConfigrations()->getShowConditionStatus()) : ?> 
                    "itemCondition": "https://schema.org/NewCondition",
                <?php endif; ?>
                <?php endif; ?>
                <?php if ($blockobj->getConfigrations()->isProductRichDataEnable()) : ?>
                <?php if ($blockobj->getConfigrations()->getProductAvaiblityStatus()) : ?>    
                    <?php if ($_product->isAvailable()) : ?>
                        "availability": "https://schema.org/InStock"
                    <?php else : ?>
                        "availability": "https://schema.org/OutStock"
                    <?php endif; ?>
                <?php endif; ?>
                <?php endif; ?>
                        ,"seller": {
                  "@type": "Organization",
                  "name": "Executive Objects"
                }
            }
        <?php } ?> 
            <?php endforeach; ?>
        <?php } else { ?>
        {
        "@type": "Offer",
        "url": "<?php echo $this->getUrl(); ?>",
        "priceCurrency": "<?php echo $currencycode ; ?>",
        <?php if (!empty($specialprice)) { ?>
            "price":  <?php echo __(number_format((float)$_product->getFinalPrice(), 2, '.', '')); ?>,   
            "priceValidUntil": "<?php echo $specialtodate ; ?>",
        <?php } else { ?>
        "price":  <?php echo __(number_format((float)$_product->getFinalPrice(), 2, '.', '')); ?>,
        <?php } ?>
    <?php if ($blockobj->getConfigrations()->isProductRichDataEnable()) : ?>
        <?php if ($blockobj->getConfigrations()->getShowConditionStatus()) : ?> 
            "itemCondition": "https://schema.org/NewCondition",
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($blockobj->getConfigrations()->isProductRichDataEnable()) : ?>
        <?php if ($blockobj->getConfigrations()->getProductAvaiblityStatus()) : ?>    
            <?php if ($_product->isAvailable()) : ?>
                "availability": "https://schema.org/InStock",
            <?php else : ?>
                "availability": "https://schema.org/OutStock",
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
        "seller": {
          "@type": "Organization",
          "name": "Executive Objects"
        }
     }
        <?php } ?>
     ]
    }
</script>
<?php if ($blockobj->getConfigrations()->isBreadcrumsEnable()) : ?>
    <?php $crumbs = $blockobj->getCrumbs($_product, $_product->getId()); ?>
    <?php $limit = count($crumbs); ?>
    <?php if ($crumbs && is_array($crumbs)) : ?>
        <script type="application/ld+json">
            {
              "@context": "https://schema.org",
              "@type": "BreadcrumbList",
              "itemListElement": [
                <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <?php if ($counter != $limit) : ?>
                    {
                    "@type": "ListItem",
                    "position": <?php echo $counter ?>,
                    "name": "<?php echo $crumbInfo['label']; ?>",
                    "item": "<?php echo $crumbInfo['link']; ?>"
                    },
                <?php else : ?>
                    {
                    "@type": "ListItem",
                    "position": <?php echo $counter ?>,
                    "name": "<?php echo $crumbInfo['label']; ?>",
                    "item": "<?php echo $crumbInfo['link']; ?>"
                    }
                <?php endif; ?>
              
                <?php $counter++ ?>
                <?php endforeach; ?>
              ]
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php
$counter = 1;
?>            <?php
            endforeach;?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php echo $this->getLayout()->createBlock("Mageants\Richsnippets\Block\Richsnippets")->setTemplate("Mageants_Richsnippets::searchbox.phtml")->toHtml();?>
<?php echo $this->getLayout()->createBlock("Mageants\Richsnippets\Block\Richsnippets")->setTemplate("Mageants_Richsnippets::organization.phtml")->toHtml();?>