<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magestore\FulfilSuccess\Block\Adminhtml\PackRequest\ViewModal $block */
?>
<div id="<?php echo $block->getModalId() ?>"></div>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        "mage/mage",
        "mage/validation",
        "loadingPopup"
    ], function ($) {
        $('#<?php echo $block->getModalId() ?>').modal(
            {
                type: 'slide',
                modalClass: 'mage-new-video-dialog form-inline',
                title: $.mage.__('<?php echo $block->getTitle()?>'),
                buttons: [
                ]
            }
        )
    });

</script>
