<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * @var \Magestore\FulfilSuccess\Block\Adminhtml\PackRequest\Detail\Items\DefaultRenderer $block
 */
$_item = $block->getItem() ?>
<!--<tr>-->
<!--    <td class="col-product">--><?php //echo $block->getColumnHtml($_item, 'name') ?><!--</td>-->
<!--    <td class="col-barcode">--><?php //echo $block->getColumnHtml($_item, 'barcode') ?><!--</td>-->
<!--    <td class="col-qty">--><?php //echo $block->getColumnHtml($_item, 'qty') ?><!--</td>-->
<!--    <td class="col-packed-qty">--><?php //echo $block->getColumnHtml($_item, 'picked_qty') ?><!--</td>-->
<!--</tr>-->


<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var $block \Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer */ ?>

<?php $parentItem = $block->getItem() ?>
<?php $items = $block->getChildren($parentItem); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php if ($block->getOrderOptions() || $parentItem->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item): ?>
    <?php $block->setPriceDataObject($_item) ?>
    <?php if ($_item->getOrderItem()->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <tr>
                <td class="col-product"><div class="option-label"><?php /* @escapeNotVerified */ echo $attributes['option_label'] ?></div></td>
                <td class="col-product">&nbsp;</td>
                <td class="col-qty last">&nbsp;</td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr class="<?php echo(++$_index == $_count && !$_showlastRow) ? 'border' : '' ?> data-row">
        <?php if (!$_item->getOrderItem()->getParentItem()): ?>
            <td class="col-product">
                <div class="product-title"><?php echo $block->escapeHtml($_item->getName()) ?></div>
                <div class="product-sku-block">
                    <span><?php /* @escapeNotVerified */ echo __('SKU') ?>:</span>
                    <?php echo implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))); ?>
                </div>
            </td>
        <?php else: ?>
            <td class="col-product"><div class="option-value"><?php echo $block->getValueHtml($_item)?></div></td>
        <?php endif; ?>
        <td class="col-barcode">
            <?php if ($block->isShipmentSeparately($_item)): ?>
                <?php echo $block->getColumnHtml($_item, 'barcode') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-qty">
            <?php if ($block->isShipmentSeparately($_item)): ?>
                <?php echo $block->getColumnHtml($_item, 'qty') ?>
                <?php $parentOrderId = $_item->getOrderItemId(); ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-packed-qty last">
            <?php if ($block->isShipmentSeparately($_item)): ?>
                <?php echo $block->getColumnHtml($_item, 'picked_qty') ?>
                <input type="hidden" class="pack-item" value="<?php /* @escapeNotVerified */ echo $_item->getOrderItemId(); ?>">
            <?php else: ?>
                <?php if (!$block->isPackedRequest()): ?>
                    <input type="hidden" class="bundle-qty" value="<?php echo $block->getChildrenQty($_item) ?>">

                    <input type="number"
                           min="0"
                           name="qty"
                           disabled="true"
                           value="<?php /* @escapeNotVerified */ //echo $block->getChildrenQty($_item); ?>"
                           class="input-text admin__control-text qty-item child-qty-<?php /* @escapeNotVerified */ echo $parentOrderId; ?> qty">
                <?php else: ?>
                    &nbsp;
                <?php endif; ?>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr class="border">
        <td class="col-product">
            <?php if ($block->getOrderOptions($_item->getOrderItem())): ?>
                <dl class="item-options">
                    <?php foreach ($block->getOrderOptions($_item->getOrderItem()) as $option): ?>
                        <dt><?php /* @escapeNotVerified */ echo $option['label'] ?></dt>
                        <dd>
                            <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                                <?php /* @escapeNotVerified */ echo $option['value'];?>
                            <?php else: ?>
                                <?php echo $block->truncateString($option['value'], 55, '', $_remainder);?>
                                <?php if ($_remainder):?>
                                    ... <span id="<?php /* @escapeNotVerified */ echo $_id = 'id' . uniqid()?>"><?php /* @escapeNotVerified */ echo $_remainder ?></span>
                                    <script>
                                        require(['prototype'], function(){

                                            $('<?php /* @escapeNotVerified */ echo $_id ?>').hide();
                                            $('<?php /* @escapeNotVerified */ echo $_id ?>').up().observe('mouseover', function(){$('<?php /* @escapeNotVerified */ echo $_id ?>').show();});
                                            $('<?php /* @escapeNotVerified */ echo $_id ?>').up().observe('mouseout',  function(){$('<?php /* @escapeNotVerified */ echo $_id ?>').hide();});

                                        });
                                    </script>
                                <?php endif;?>
                            <?php endif;?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
            <?php echo $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <td class="col-barcode">&nbsp;</td>
        <td class="col-qty">&nbsp;</td>
        <td class="col-packed-qty last">&nbsp;</td>
    </tr>
<?php endif; ?>

<!--<script>-->
<!--    require([-->
<!--        "Magestore_FulfilSuccess/js/packrequest/detail/bundle",-->
<!--    ], function(){-->
<!--        var bundle = new bundle({-->
<!--            packQtyClass : 'qty-item',-->
<!--            packItemClass : 'pack-item',-->
<!--        });-->
<!---->
<!--    });-->
<!--</script>-->