<?php
/**
 * @category Mageants StoreLocator
 * @package Mageants_StoreLocator
 * @copyright Copyright (c) 2017 Mageants
 * @author Mageants Team <support@Mageants.com>
 */
?>
<div class="map">
<?php
$latitude='';
$distance=0;
$current=0;
$counter = 0;
$distanceCollection = [];
$distanceCollectionSort = [];
unset($StoreCollection);
if ($block->getRequest()->getPostValue()) {
    $data=$block->getRequest()->getPostValue();
    if (isset($data['current'])) {
        $current=$data['current'];
        $distance=$data['distance'];
        if ($distance != 0) {
              $StoreCollection=$block->getRangeStoreCollection($current, $distance);
            if ($StoreCollection instanceof Countable > 0) {
                foreach ($StoreCollection as $store) {
                    $dist=$block->getDistance($current, $store['latitude'], $store['longitude'], "K", $distance);
                    $store->setData('distance', $dist);
                    $store['distance'] = $dist;
                    $distanceCollection[$counter] = $store->getData();
                    $counter++;
                }
                $totalCollection = sizeof($distanceCollection); //@codingStandardsIgnoreLine
                for ($i = 0; $i < $totalCollection - 1; $i++) {
                    for ($j=0; $j < $totalCollection - $i - 1; $j++) {
                        if ($distanceCollection[$j]['distance'] > $distanceCollection[$j + 1]['distance']) {
                            $distanceCollectionSort = $distanceCollection[$j];
                            $distanceCollection[$j] = $distanceCollection[$j + 1];
                            $distanceCollection[$j + 1] = $distanceCollectionSort;
                        }
                    }
                }
                unset($StoreCollection);
                $StoreCollection =  $distanceCollection;
            }
        } else {
            $StoreCollection=$block->getStoreCollection();
        }
    } else {
           $storename=$data['storename'];
           $countryid=$data['countryid'];
           $state=$data['state'];
           $city=$data['city'];
           $zipcode=$data['zipcode'];
           $StoreCollection=$block->getAreaStoreCollection($storename, $countryid, $state, $city, $zipcode);
    }
} else {
          $StoreCollection=$block->getStoreCollection();
}
    $locations="[";
    $markTemplateText=[];
    $i=0;
foreach ($StoreCollection as $store) {
    if ($i==0) {
        $latitude=$store['latitude'];
    }
        $markTemplate=$block->getStoreMarkerTemplate();
        $icon='';
        if ($store['icon'] != null) { //@codingStandardsIgnoreLine
        $src=$image="";
        $icon=$block->getUrl('pub/media/').$store['icon'];
        } //@codingStandardsIgnoreLine
      $locations .="['".$store['address']."',".$store['latitude'].",".$store['longitude'].",".$store['store_id'].",'".$icon."'],";
      $markTemplate=str_replace("{{name}}", $store['sname'], $markTemplate);
      if ($store['image'] != null) { //@codingStandardsIgnoreLine
          $src=$image="";
          $src=$block->getUrl('pub/media/').$store['image'];
          $image='<img height="50px" width="50px" src="'.$src.'" />';
      } else { //@codingStandardsIgnoreLine
          $image="";
          $image='<img height="50px" width="50px" src="'.$block->getViewFileUrl('Mageants_StoreLocator::images/map_with_pin.png').'" />';
      } //@codingStandardsIgnoreLine
      $markTemplate=str_replace("{{image}}", $image, $markTemplate);
      $markTemplate=str_replace("{{city}}", $store['city'], $markTemplate);
      $markTemplate=str_replace("{{country}}", $store['country'], $markTemplate);
      $markTemplate=str_replace("{{postcode}}", $store['postcode'], $markTemplate);
      $markTemplate=str_replace("{{region}}", $store['region'], $markTemplate);
      $markTemplate=str_replace("{{address}}", $store['address'], $markTemplate);
      $markTemplate=str_replace("{{email}}", $store['email'], $markTemplate);
      $markTemplate=str_replace("{{phone}}", $store['phone'], $markTemplate);
      $markTemplate=str_replace("{{website}}", $store['link'], $markTemplate);
      $markTemplate=str_replace("'", '"', $markTemplate);
      //@codingStandardsIgnoreLine
      $markTemplateText[] = array("$markTemplate");
    } //@codingStandardsIgnoreLine
$locations .= "]";
?>
   <div id="map" style="width: 100%; height: 580px;"></div>
   <div id="pono" style="width: 100%; height: 580px;display: none; "></div>
   <?php //@codingStandardsIgnoreLine ?>
   <script async defer type="text/javascript">
                var locations=<?php
                if ($locations!='[]') :
                  /* @noEscape */  echo $locations;
                else :
                    echo "[['ahemdabad',-33.890542, 151.274856,1,'']]";
                endif; ?>;
                var markTemplateText=[];
                var markerFlag=0;
                markTemplateText =<?php
                //@codingStandardsIgnoreLine
                if (sizeof($markTemplateText)>0) {
                  /* @noEscape */  echo json_encode($markTemplateText);
                } else {
                    echo "['ee','ee']";
                } ?>;
                markerFlag =<?php
                //@codingStandardsIgnoreLine
                if (sizeof($markTemplateText)>0) {
                    echo "1";
                } else {
                    echo "0";
                } ?>;
                var myLatlng = new google.maps.LatLng(locations[0][1], locations[0][2]);
                var myOptions = {
                    zoom: <?php
                    if ($latitude!='') {
                        echo "20";
                    } else {
                        echo "3";
                    } ?>,
                    center: myLatlng,
                    minZoom: 1,
                    panControl: true,
                    zoomControl: true,
                    mapTypeControl: true,
                    streetViewControl: true,
                    overviewMapControl: true,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
                var map = new google.maps.Map(document.getElementById('map'), myOptions);
                var infowindow = new google.maps.InfoWindow();
                var marker, i;
                var gmarkers = [];
          function createMarker(latlng, html,icon,i) {
              var marker = new google.maps.Marker({
                  position: latlng,
                  animation: google.maps.Animation.DROP
              });
              marker.setMap(map);
              google.maps.event.addListener(marker, 'click', function() {
                  jQuery(".list-store-container #gmarkers"+i).trigger("click");

              var container = jQuery('div.store-list-all'),
              scrollTo = jQuery("#gmarkers"+i);

             container.animate({
                  scrollTop: scrollTo.offset().top - container.offset().top + container.scrollTop()
              });
          });

          google.maps.event.addListener(marker, 'mouseover', function() {
              infowindow.setContent(html);
              infowindow.open(map, marker);
          });
          if(icon!='')
          {
              var imageicon = {
                  url: icon,
                  scaledSize: new google.maps.Size(26, 36),
                  origin: new google.maps.Point(0, 0),
                  anchor: new google.maps.Point(0, 32)
              };
              marker.setIcon(imageicon);
          }
          if(i==0)
          {
              google.maps.event.trigger(marker,'mouseover');
          }

          return marker;
        }
        if(markerFlag==1){
            for (var i = 0; i < locations.length; i++) {
                gmarkers[i] = createMarker(new google.maps.LatLng(locations[i][1], locations[i][2]),markTemplateText[i][0],locations[i][4],i);    
            }   
        }
</script>
</div>