<?php
/**
 * @category Mageants StoreLocator
 * @package Mageants_StoreLocator
 * @copyright Copyright (c) 2017 Mageants
 * @author Mageants Team <support@Mageants.com>
 */
$apiKey=$block->getApiKey();
$store_id = $block->getRequest()->getParam("id");
$distance=0;
$current=0;
if ($block->getRequest()->getParam("id")) {
    $id=$block->getRequest()->getParam("id");
    if ($id != '') {
        $collection=$block->getStoreById($id);
    } else {
        $collection=$block->getStoreCollection();
    }
} else {
    $collection=$block->getStoreCollection();
}
?>
<div id="store_list" class="list-store-box col-sm-4  pull-left">
    <div  class="page-title">
        <div class="list-store ">
            <div class="list-store-container disable-ul">
            <?php if (sizeof($collection)  == 0) { //@codingStandardsIgnoreLine
                echo "<strong style='margin-left:5px;'>No Store Found</strong>";
            //@codingStandardsIgnoreLine
            } else {
    ?>
<?php	$inc=0;   foreach ($collection as $store) : ?>
            <?php if ($store['image'] != null) {
                $imageUrl=$block->getUrl('pub/media/').$store['image'];
            //@codingStandardsIgnoreLine
            } else {
    $imageUrl=$block->getViewFileUrl('Mageants_StoreLocator::images/map_with_pin.png');
//@codingStandardsIgnoreLine
            } ?>    
                <div class="allstores-content"> 
                <div class="storepage-title">
                    <h2 class="title">
                    <span class="" aria-hidden="true"></span>
                    <span>Store list</span>
                    <span class="number-store pull-right"><?php /* @noEscape */ echo $collection instanceof Countable;
                    /* @noEscape */ echo __(" Stores");?> </span>
                    </h2>
                </div>
                    <div class="mainstores show-tag-li store-item store-40 store-active <?php if ($inc==0) { /* @noEscape */
                            //@codingStandardsIgnoreLine    
                             echo "left-active"; } $inc++; ?>"  
                             data-store-id="<?php /* @noEscape */ echo $store['id']; ?>" data-store-index="0" 
                             data-latitude="<?php /* @noEscape */ echo $store['latitude']; ?>" data-longitude="<?php /* @noEscape */ echo $store['longitude']; ?>" data-address="<?php /* @noEscape */ echo $store['address']; ?>">
                    <div class="mainstorlist">
                        <div class="cols-3">
                            <div class="tag-store">
                                <img src="<?php /* @noEscape */ echo $imageUrl; ?>">
                                <p class="text-center"></p>
                            </div>                      
                        </div>
                        <div class="cols-9">
                            <div class="tag-content">       
                            <h4>
                                <a id="store-link" class="title-store store-link" onclick="return false;"><?php /* @noEscape */ echo __($store['sname']); ?>
                                    <input type="hidden" class="sl-latitude" value="<?php /* @noEscape */ echo __($store['latitude']); ?>">
                                    <input type="hidden" class="sl-longitude" value="<?php /* @noEscape */ echo __($store['longitude']); ?>">
                                </a>
                                </h4>
                            <p class="address-store"><?php /* @noEscape */ echo $store['address'].",".$store['region']." ".$store['city'].",".$store['country']; ?></p>
                            <p class="phone-store"><?php /* @noEscape */ echo $store['phone']; ?></p>
                            <div class="tagstore-content">
                            <a data-lat="<?php /* @noEscape */ echo $store['latitude']; ?>" data-long="<?php /* @noEscape */ echo $store['longitude']; ?>" class="btn-link streetview"><span ><?php /* @noEscape */ echo __("Street View"); ?></span></a>
                            <a herf="#" data-lat="<?php /* @noEscape */ echo $store['latitude']; ?>" data-long="<?php /* @noEscape */ echo $store['longitude']; ?>" data-div-no="<?php /* @noEscape */ echo $inc; ?>" class="btn-link direction" ><span ><?php /* @noEscape */ echo __("Direction"); ?></span></a>
                            </div>
                            </div>
                            
                        </div>
                        
                    </div>
                    
                    <div data-div-no="<?php /* @noEscape */ echo $inc; ?>" class="option-direction custom-popup " style="padding: 0px;display: none;">
                        
                        <div id="directions-tool" class="directions-tool">
                            <ul class="vertical text-center">
                                <li class="travel car active" data-traveling="DRIVING"><span>D</span></li>
                                <li class="travel bus" data-traveling="TRANSIT"><span>T</span></li>
                                <li class="travel walk" data-traveling="WALKING"><span>W</span></li>
                                <li class="travel bicycle" data-traveling="BICYCLING"><span>B</span></li>
                            </ul>
                            <div class="form-inputs">
                                <input class="form-control origin originA start storelocator-originA-start" name="originA" isstart="true" autocomplete="off"  id="storelocator-originA-start" placeholder="Enter a location" type="text"> <br/>
                                <input class="form-control origin originB end" id="storelocator-originA-end" readonly="true" name="originB" autocomplete="off" value="<?php /* @noEscape */ echo $store['address'].",".$store['city'].",".$store['country']; ?>" disabled type="text"> <br/>
                            </div>
                            <div class="directions-panel" id="directions-panel"></div>
                        </div>
                        <div class="box-input direction-go">
                            <button class="get-direction action primary pull-right" id="get_direction" title="Get Directions" type="submit">
                                <span><?php /* @noEscape */ echo __("Go"); ?></span>
                            </button>
                        </div>
                    </div>
                </div>
                </div>
                
                <div class="store-timings">
                    <div id="open_hour" class="open_hour">
                        <div class="storepage-title opening">
                        <h2 class="title"><span><?php /* @noEscape */ echo __("Opening hours"); ?></span></h2>
                        </div>

                        <div class="table-responsive">
                            <table class="table table-time-schedule">
                                <tbody>
                                    <tr id="sun_tr">
                                        <td class="time-label" style="text-align: center; width: 20%;"><?php  /* @noEscape */ echo __("Sun:"); ?> </td>
                                        <td></td>
                                        <?php if (!empty($store['sun_open'])) { ?>
                                        <td><?php /* @noEscape */ echo __("Open"); ?>
                                            <table style="display: none;" class="sun_tr">
                                                <tr>
                                                  <td><?php /* @noEscape */ echo __("Opening Time :"); ?> <?php /* @noEscape */ echo str_replace(",", ":", $store['sun_otime']);?></td>
                                                  <td><?php /* @noEscape */ echo __("Closing Time :"); ?> <?php /* @noEscape */ echo str_replace(",", ":", $store['sun_ctime']); ?></td>
                                                </tr>
                                          </table>
                                        </td>
                                        <td id="sun_tr" class="open_schedule"><i class="arrow down"></i></td>
                                        <?php } else {?>
                                        <td><?php /* @noEscape */ echo __("Closed"); ?> </td>
                                        <td></td>
                                        <?php } ?>
                                    </tr>
                                    <tr id="mon_tr">
                                        <td class="time-label" style="text-align: center; width: 20%;"><?php /* @noEscape */ echo __("Mon:"); ?></td>
                                        <td></td><?php if (!empty($store['mon_open'])) { ?>
                                        <td>Open
                                            <table style="display: none;" class="mon_tr">
                                            <tr>
                                              <td><?php /* @noEscape */ echo __("Opening Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['mon_otime']); ?></td>
                                              <td><?php /* @noEscape */ echo __("Closing Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['mon_ctime']); ?></td>
                                            </tr>
                                            </table>
                                        </td>
                                        <td id="mon_tr" class="open_schedule"><i class="arrow down"></i></td>
                                        <?php /* @codingStandardsIgnoreLine */ } else {?>
                                        <td><?php /* @noEscape */ echo __("Closed"); ?> </td>
                                        <td></td>
                                        <?php } ?>
                                    </tr>
                                    <tr id="tue_tr">
                                        <td class="time-label" style="text-align: center; width: 20%;"><?php /* @noEscape */ echo __("Tue:"); ?></td>
                                        <td></td><?php if (!empty($store['tue_open'])) { ?>
                                        <td>Open <table style="display: none;" class="tue_tr">
                                            <tr>
                                              <td><?php /* @noEscape */ echo __("Opening Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['tue_otime']); ?></td>
                                              <td><?php /* @noEscape */ echo __("Closing Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['tue_ctime']); ?></td>
                                            </tr>
                                        </table>
                                      </td>
                                      <td id="tue_tr" class="open_schedule"><i class="arrow down"></i></td>
                                                <?php /* @codingStandardsIgnoreLine */ } else { ?>
                                        <td><?php /* @noEscape */ echo __("Closed"); ?> </td>
                                        <td></td>
                                                <?php } ?>
                                    </tr>
                                    <tr id="wed_tr">
                                        <td class="time-label" style="text-align: center; width: 20%;"><?php /* @noEscape */ echo __("Wed:"); ?></td>
                                        <td></td><?php if (!empty($store['wed_open'])) { ?>
                                        <td>Open
                                            <table style="display: none;" class="wed_tr">
                                                <tr>
                                                  <td><?php /* @noEscape */ echo __("Opening Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['wed_otime']); ?></td>
                                                  <td><?php /* @noEscape */ echo __("Closing Time :"); ?><?php  /* @noEscape */ echo str_replace(",", ":", $store['wed_ctime']); ?></td>
                                                </tr>
                                                </table>
                                          </td>
                                          <td id="wed_tr" class="open_schedule"><i class="arrow down"></i></td>
                                                <?php  /* @codingStandardsIgnoreLine */ } else {?>
                                        <td><?php /* @noEscape */ echo __("Closed"); ?> </td>
                                        <td></td>
                                                <?php } ?>
                                    </tr>
                                    <tr id="thu_tr">
                                        <td class="time-label" style="text-align: center; width: 20%;"><?php /* @noEscape */ echo __("Thur:"); ?></td>
                                        <td></td><?php if (!empty($store['thu_open'])) { ?>
                                        <td>Open
                                            <table style="display: none;" class="thu_tr">
                                                    <tr>
                                                      <td><?php /* @noEscape */ echo __("Opening Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['thu_otime']); ?></td>
                                                      <td><?php /* @noEscape */ echo __("Closing Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['thu_ctime']); ?></td>
                                                    </tr>
                                                </table>
                                          </td>
                                          <td id="thu_tr" class="open_schedule"><i class="arrow down"></i></td>
                                                <?php /* @codingStandardsIgnoreLine */ } else {?>
                                        <td><?php /* @noEscape */ echo __("Closed"); ?> </td>
                                        <td></td>
                                                <?php } ?>
                                    </tr>
                                    <tr id="fri_tr">
                                        <td class="time-label" style="text-align: center; width: 20%;"><?php /* @noEscape */ echo __("Fri:"); ?></td>
                                        <td></td><?php if (!empty($store['fri_open'])) { ?>
                                        <td>Open
                                            <table style="display: none;" class="fri_tr">
                                                <tr>
                                                  <td><?php /* @noEscape */ echo __("Opening Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['fri_otime']); ?></td>
                                                  <td><?php /* @noEscape */ echo __("Closing Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['fri_ctime']); ?></td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td id="fri_tr" class="open_schedule"><i class="arrow down"></i></td>
                                                <?php /* @codingStandardsIgnoreLine */ } else { ?>
                                        <td><?php /* @noEscape */ echo __("Closed"); ?> </td>
                                        <td></td>
                                                <?php } ?>
                                    </tr>
                                    <tr id="sat_tr">
                                        <td class="time-label" style="text-align: center; width: 20%;"><?php /* @noEscape */ echo __("Sat:"); ?></td>
                                        <td></td><?php if (!empty($store['sat_open'])) { ?>
                                        <td>Open
                                            <table style="display: none;" class="sat_tr">
                                                <tr>
                                                  <td><?php /* @noEscape */ echo __("Opening Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['sat_otime']); ?></td>
                                                  <td><?php /* @noEscape */ echo __("Closing Time :"); ?><?php /* @noEscape */ echo str_replace(",", ":", $store['sat_ctime']); ?></td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td id="sat_tr" class="open_schedule"><i class="arrow down"></i></td>
                                        <?php /* @codingStandardsIgnoreLine */ } else { ?>
                                        <td><?php /* @noEscape */ echo __("Closed"); ?></td>
                                        <td></td>
                                        <?php
                                        /* @codingStandardsIgnoreLine */
                                        }
                                        ?>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>                  
                </div>
<?php /* @codingStandardsIgnoreLine */ endforeach; } ?>  
            </div>
        </div>
    </div>
</div>	
<?php //@codingStandardsIgnoreLine ?>
<script>
require(["jquery"], function($){
    $(document).ready(function($) {

        $(".table-time-schedule td.open_schedule").click(function(){
            var id=$(this).attr("id");
            jQuery("table."+id).slideToggle("slow");
            $(this).find(".arrow").toggleClass("down");
        });

        $(".btn-link.streetview").click(function(e){
            e.stopImmediatePropagation();
        var latitude=jQuery(this).attr("data-lat");
        var longitude=jQuery(this).attr("data-long");
        var baltimore = new google.maps.LatLng(latitude, longitude);
        var panoramaOptions = {
            position: baltimore,
            pov: {
              heading: 34,
              pitch: 10
            }
          };
          var panorama = new google.maps.StreetViewPanorama(document.getElementById('pono'), panoramaOptions);
          jQuery("#map").hide();
          jQuery("#pono").show();
        });

        $(".btn-link.direction").click(function(e){
            e.stopImmediatePropagation();
            var divno=$(this).attr("data-div-no");
            $(".option-direction.active").removeClass("active");
            jQuery("div[data-div-no='"+divno+"']").addClass("active");

        });

        $("li.travel").click(function(e){
            e.preventDefault();
            jQuery(".travel.active").removeClass("active");
            jQuery(this).addClass("active");
        });
        
        $(".show-tag-li.store-item.store-40.store-active").click(function($){
            var latitude=parseFloat(jQuery(this).find(".sl-latitude").val());
            var longitude=parseFloat(jQuery(this).find(".sl-longitude").val());
            map.panTo(new google.maps.LatLng(latitude,longitude));
            jQuery("#map").show();
            jQuery("#pono").hide();
        });

        $("#get_direction").click(function(e){
            e.preventDefault();
            var origin=jQuery("#storelocator-originA-start").val();
            var destination=jQuery("#storelocator-originA-end").val();
            if(origin=='')
            {
                jQuery("#storelocator-originA-start").css("box-shadow","0 0 3px 1px red");
            }
            else
            {
                var directionsService = new google.maps.DirectionsService();
                var directionsDisplay = new google.maps.DirectionsRenderer();
                var type=jQuery(".travel.active").attr("data-traveling");
                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom:5,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                });
                
                directionsDisplay.setMap(map);
                directionsDisplay.setPanel(document.getElementById('directions-panel'));
                
                var request = {
                    origin: origin, 
                    destination: destination,
                    travelMode: google.maps.TravelMode[type]
                };

                directionsService.route(request, function(response, status) {
                    if (status == google.maps.DirectionsStatus.OK) {
                        directionsDisplay.setDirections(response);
                    }
                });
            }
        });
        jQuery('.storelocator-originA-start').each(function(){
            new google.maps.places.Autocomplete(
              this, {
                types: ['geocode']
            });
        });

    });
});
</script>
<style type="text/css">
    i {
    border: solid black;
    border-width: 0 3px 3px 0;
    display: inline-block;
    padding: 3px;
}
.arrow {
    transform: rotate(-135deg);
    -webkit-transform: rotate(-135deg);
}

.down {
    transform: rotate(45deg);
    -webkit-transform: rotate(45deg);
}
</style>