<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var \Magestore\AdjustStock\Block\Adminhtml\Import\NoticeMessage $block*/
$numberSkuInvalid = $block->getNumberSkuInvalid();
if (!$numberSkuInvalid) {
    $numberSkuInvalid = 0;
}
?>
<?php if ($block->isHasError()) :?>
<div class="messages">
    <div class="message message-error message-in-rating-edit">
        <div>
            <b><?php /* @escapeNotVerified */echo __('Invalid data'); ?></b>
        </div>
        <div>
            <?php /* @escapeNotVerified */
            if ($numberSkuInvalid) {
                echo __('Data includes non-existent SKU(s)! Please try again! You can download the list of invalid SKU(s) ');
            }
            ?>
            <a href="<?php echo $block->getInvalidFileCsvUrl();?>"><?php echo __('here');?></a>
            <?php echo __(' to modify and try to import them again.'); ?>
        </div>
    </div>
</div>
<?php endif;?>
