<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');// @codingStandardsIgnoreLine
$customStockStHelper = $this->helper('Mageants\CustomStockStatus\Helper\Data');// @codingStandardsIgnoreLine
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= /* @noEscape */ __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="item product product-item">' :
                 '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @noEscape */ $_product->getProductUrl() ?>" 
                        class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @noEscape */ $_product->getProductUrl() ?>">
                                <?= /* @noEscape */ $_helper->productAttribute(
                                    $_product,
                                    $_product->getName(),
                                    'name'
                                ) ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                         <?php if ($_product->isAvailable()):?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>
                         <?php /* Start Custom Changes */ ?>
                                    <?= /* @noEscape */ $block->getLayout()
                                          ->createBlock(\Mageants\CustomStockStatus\Block\Product\Customstatus::class)
                                          ->setData('product', $_product)
                                          ->setTemplate('Mageants_CustomStockStatus::customstock/list.phtml')
                                          ->toHtml();
                                    ?>
                                 <?php /* End Custom Changes */ ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"
                            <?= /* @noEscape */ strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary" 
                                <?= /* @noEscape */ strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku=" 
                                        <?= /* @noEscape */ $_product->getSku() ?>" 
                                        action="<?= /* @noEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" 
                                            value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" 
                                            name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" 
                                            value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]// @codingStandardsIgnoreLine ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @noEscape */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if (!$customStockStHelper->getHideStockStatus()): ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available">
                                                    <span><?= /* @noEscape */ __('In stock') ?></span>
                                                </div>
                                            <?php else: ?>
                                                <div class="stock unavailable">
                                                    <span><?= /* @noEscape */ __('Out of stock') ?></span>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"
                                <?= /* @noEscape */ strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute(
                                        $_product,
                                        $_product->getShortDescription(),
                                        'short_description'
                                    ) ?>
                                    <a href="<?= /* @noEscape */ $_product->getProductUrl() ?>" 
                                        title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= /* @noEscape */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @noEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
