<?php
/**
 * @category Mageants GiftCertificate
 * @package Mageants_GiftCertificate
 * @copyright Copyright (c) 2016 Mageants
 * @author Mageants Team <support@mageants.com>
 */

$_item = $block->getItem();
?>
<input type="hidden" name="<?php echo $_item->getProduct()->getId(); ?>" class="categoryids" id="categoryids" value='<?php foreach ($_item->getProduct()->getCategoryIds() as $catid){ echo $catid.","; } echo $_item->getRowTotal();  ?> '/>
<?php

if( $_item->getProductType()=='giftcertificate'):
	if($this->getcustomerId() != null )
	{
		$giftquote=$this->getGiftQuoteItems($this->getcustomerId())->getData();
	}
	else
	{
		$giftquote=$this->getNotLoggedInGiftQuoteItems($this->geNotLoggedIntcustomerId())->getData();	
	}

$product = $_item->getProduct(); // Get cart product details
$additional_data = $block->getAdditionalData(); // Get cart product additionl details defined in block page
$saveQuote=$this->saveQuote($_item->getQuoteId());
$count=1;
?>
<input type="hidden" id="base-gift-url" value="<?php echo $this->getUrl(); ?>"/>

<?php
foreach($giftquote as $quote):
	if($quote['product_id']==$product->getId()):
?>

<div class="additional-info">
	<div>
		<span><?php echo $additional_data; ?> </span>
	</div>
	<div>
		<span><?php echo __('Gift Card Value:'); echo $_item->getCustomPrice();?></span>
	</div>
	<div>
		<span><?php echo __('Gift Card Type:'); echo $this->getCardType($quote['card_types']); ?></span>
	</div>
	<div>
		<span><?php echo __('Gift Card Sender:'); echo $quote['sender_name']; ?></span>
	</div>
	<div>
		<input type="hidden" class="quote-id" value=<?php echo $quote['id']; ?> />
		<input type="hidden" name="productid" id="productid" value='<?php echo $_item->getProduct()->getId(); ?>'/>
		<a href="javascript:void(0)" class="deletequote">Remove</a>
	</div>
	<div class="loading-cart"></div>
</div>	
<hr/>
<?php
	$count++;
	endif;
endforeach;
endif;	

?>
<script type="text/javascript">
    require(['jquery','giftcertificate'],function($){
    });
</script>
