<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var \Magestore\FulfilSuccess\Block\Adminhtml\PackRequest\Detail\Items $block
 */
$_order = $block->getOrder() ?>

<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary order-shipment-table">
        <thead>
        <tr class="headings">
            <th class="col-product"><span><?php /* @escapeNotVerified */
                    echo __('Product') ?></span></th>
            <th class="col-barcode column-width-30"><span><?php /* @escapeNotVerified */
                    echo __('Barcode') ?></span></th>
            <th class="col-request-qty"><span><?php /* @escapeNotVerified */
                    echo __('Qty To Pack') ?></span></th>
            <th class="col-packed-qty"><span><?php /* @escapeNotVerified */
                    echo __('Packed Qty') ?></span></th>
        </tr>
        </thead>
        <?php $_items = $block->getItemsCollection(); ?>
        <?php $i = 0;
        foreach ($_items as $_item): ?>
            <?php if ($_item->getParentItem()) {
                continue;
            } else {
                $i++;
            } ?>
            <tbody class="<?php /* @noEscape */
            echo $i % 2 ? 'even' : 'odd' ?>">
            <?php echo $block->getItemHtml($_item) ?>
            <?php echo $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <div class="error-message" id="pack-error-message">
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>