<?php
/**
 * @category Mageants StoreLocator
 * @package Mageants_StoreLocator
 * @copyright Copyright (c) 2017 Mageants
 * @author Mageants Team <support@Mageants.com>
 */
//@codingStandardsIgnoreLine
$apikey=$this->helper('Mageants\StoreLocator\Helper\Data')->getConfigValue("StoreLocator/map/map_key");
?>
<div class="map" >
    <button id="getCords" style="margin-left:50px;margin-bottom:0px;" onClick="codeAddress();return false">Get Location </button><br/>
    <span ><small style="margin-bottom:20px;">Click for get LatLng from Address.</small></span>
    <br/><br/>
    <?php //@codingStandardsIgnoreLine ?>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<?php echo $apikey; ?>&v=3.20&libraries=geometry,places&sensor=false"></script>
    <div id="map" style="width: 100%; height: 500px;"></div>
    <?php //@codingStandardsIgnoreLine ?>
    <script type="text/javascript">
    var marker;
    var map;
    require([ 'jquery', ''], function(){
       jQuery(document).ready(function ($) {
        
        var $tabs=$("#post_tabs")
        if ($tabs.length) {
            var tabContent = $('#post_tabs_coordinates_section_content').get(0);
            if (tabContent) {
                $tabs.bind('tabsactivate', function(event, data) {
                    if (data.newPanel.get(0) === tabContent) {
                        var lat=jQuery("#latitude").val();
                        if(lat=""){ load(); } else { initialize();}
                    }
                });
                var lat=jQuery("#latitude").val();
                if(lat=""){ load(); } else { initialize();}
            }
        } 

    function initialize()
    {
        var lat =jQuery("#latitude").val();
        var lng =jQuery("#longitude").val();
        map = new google.maps.Map(document.getElementById('map'), {
          zoom:17,
          minZoom: 1,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        });
        if(lat!="")
        {
        marker = new google.maps.Marker({
            position:  new google.maps.LatLng(lat,lng),
            map: map
        }); 
        }
        var point = new google.maps.LatLng(lat,lng);
        map.setCenter(point);
    }
    /* google.maps.event.addDomListener(window, 'load', initialize); */
    
    function load()
    {
        var mapOptions = {
            zoom: 1,
            minZoom: 2,
            mapTypeControlOptions: {
                position: google.maps.ControlPosition.TOP_LEFT
            }
        };
        map = new google.maps.Map(document.getElementById('map'),mapOptions);
    }
        
    });
    }); 
    
    function codeAddress() {
        geocoder = new google.maps.Geocoder();
        var addres = document.getElementById("address").value;
        var city = document.getElementById("city").value;
        var region = document.getElementById("region").value;
        var country = document.getElementById("country").value;
        var address=addres+" "+city+" "+region+" "+country;

        geocoder.geocode({'address': address}, function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            jQuery("#latitude").val(results[0].geometry.location.lat());
            jQuery("#longitude").val(results[0].geometry.location.lng());
                var lat=results[0].geometry.location.lat();
                var lng=results[0].geometry.location.lng();
                var point = new google.maps.LatLng(lat,lng);
                marker = new google.maps.Marker({
                    position:  new google.maps.LatLng(lat,lng),
                    map: map
                }); 
                // marker.setPosition(point);
                map.setCenter(point);
            }    
            else {
            alert("We Can't get Co-ordination from your address. Please Re-enter your address.");
          }
        });
    }
    </script>
</div>