<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\Order\Packaging */ ?>
<div id="packaging_window">
    <div class="message message-warning" style="display: none"></div>
    <div class="message message-success" style="display: none"></div>
    <section class="admin__page-section" id="package_template" style="display:none;">
        <div class="admin__page-section-title">
            <span class="title">
                <?php /* @escapeNotVerified */ echo __('Request') ?> <span  data-role="package-number"></span>
            </span>
            <div class="actions _primary">
                <button type="button" class="action-secondary" data-action="package-save-items" onclick="packaging.packItems(this);">
                    <span><?php /* @escapeNotVerified */ echo __('Add Selected Product(s) to Request') ?></span>
                </button>
                <button type="button" class="action-secondary" data-action="package-add-items" onclick="packaging.getItemsForPack(this);">
                    <span><?php /* @escapeNotVerified */ echo __('Add Products to Request') ?></span>
                </button>
            </div>
        </div>
        <div class="admin__control-table-wrapper admin__page-subsection">
            <table class="data-table admin__control-table">
                <thead>
                    <tr>
                        <th class="col-type"><?php /* @escapeNotVerified */ echo __('Shipping Channel') ?></th>
                        <th class="col-actions">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="col-type">
                            <?php $containers = $block->getContainers(); ?>
                            <select name="package_container"
                                    class="admin__control-select">
                                <?php foreach ($block->getContainers() as $key => $value): ?>
                                    <option value="<?php /* @escapeNotVerified */ echo $key ?>" >
                                        <?php /* @escapeNotVerified */ echo $value ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td class="col-actions">
                            <button type="button" class="action-delete DeletePackageBtn" onclick="packaging.deletePackage(this);">
                                <span><?php /* @escapeNotVerified */ echo __('Delete Package') ?></span>
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
            <?php if ($block->getContentTypes()): ?>
                <table class="data-table admin__control-table" cellspacing="0">
                    <thead>
                        <tr>
                            <th><?php /* @escapeNotVerified */ echo __('Contents') ?></th>
                            <th><?php /* @escapeNotVerified */ echo __('Explanation') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <select name="content_type"
                                    class="admin__control-select"
                                    onchange="packaging.changeContentTypes(this);">
                                <?php foreach ($block->getContentTypes() as $key => $value): ?>
                                    <option value="<?php /* @escapeNotVerified */ echo $key ?>" >
                                        <?php /* @escapeNotVerified */ echo $value ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td>
                            <input name="content_type_other"
                                   type="text"
                                   class="input-text admin__control-text options-content-type disabled"
                                   disabled="disabled" />
                        </td>
                    </tr>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
        <div class="admin__page-subsection" data-role="package-items">
            <div class="grid_prepare admin__page-subsection"></div>
        </div>
    </section>
    <div id="packages_content"></div>
</div>
