<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\Order\Packaging */ ?>
<?php
$girthEnabled = 0;
?>
<script>
    require([
        "jquery",
        "prototype",
        "Magestore_OrderSuccess/js/order/ship_process",
        "Magento_Ui/js/modal/modal"
    ], function(jQuery){

        packaging = new Packaging(<?php /* @escapeNotVerified */ echo $block->getConfigDataJson() ?>);
        packaging.changeContainerType($$('select[name=package_container]')[0]);
        packaging.setConfirmPackagingCallback(function(){
            packaging.sendCreateLabelRequest();
        });
        packaging.setLabelCreatedCallback(function(response){
            setLocation("<?php /* @escapeNotVerified */ echo $block->getUrl(
                'sales/order/view',
                ['order_id' => $block->getOrderId()],
                ['order_position' => $block->getOrderPosition()]
            ); ?>");
        });
        packaging.setCancelCallback(function() {
            if ($('create_shipping_label')) {
                packaging.cleanPackages();
                $('create_shipping_label').checked = false;
                toggleCreateLabelCheckbox();
            }
        });
        packaging.setItemQtyCallback(function(itemId){
            var item = $$('[name="shipment[items]['+itemId+']"]')[0];
            console.log(item);
            if (item && !isNaN(item.value)) {
                return item.value;
            }
        });
        jQuery('#packaging_window').modal({
            type: 'slide',
            title: '<?php /* @escapeNotVerified */ echo __('Create Fulfillment Request') ?>',
            buttons: [{
                text: '<?php /* @escapeNotVerified */ echo __('Cancel') ?>',
                'class': 'action-secondary',
                click: function () {
                    packaging.cancelPackaging();
                    this.closeModal();
                }
            }, {
                text: '<?php /* @escapeNotVerified */ echo __('Save') ?>',
                    'attr': {'disabled':'disabled', 'data-action':'save-packages'},
                'class': 'action-primary _disabled',
                click: function () {
                    packaging.confirmPackaging();
                }
            }, {
                text: '<?php /* @escapeNotVerified */ echo __('Add Fulfillment Request') ?>',
                'attr': {'data-action':'add-packages'},
                'class': 'action-secondary',
                click: function () {
                    packaging.newPackage();
                }
            }]
        });
    });
</script>
<?php include ($block->getTemplateFile('Magestore_OrderSuccess::order/shipprocess/popup_content.phtml')) ?>
