<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var $block \Magestore\Stocktaking\Block\Adminhtml\Stocktaking\Edit\Steps\Timeline */
?>
<div data-role="steps-wizard-main" class="steps-wizard <?= /* @noEscape */ $block->getData('config/dataScope') ?>"
     data-bind="scope: '<?= /* @noEscape */  $block->getComponentName()?>'">
    <div data-role="messages" class="messages"></div>
    <div data-role="steps-wizard-controls" class="steps-wizard-navigation">
        <ul class="nav-bar">
            <?php foreach ($block->getSteps() as $step): ?>
                <?php
                $isActive = '';
                ?>
                <?php
                if ($step->getComponentName() == $block->getCurrentStep()):
                    $isActive = 'class="active"';
                endif;
                ?>
                <li data-role="collapsible" <?= /* @noEscape */ $isActive ?> >
                    <a href="#<?= /* @noEscape */  $step->getComponentName() ?>">
                        <?= /* @noEscape */  $step->getCaption() ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
