<style type="text/css">
    #magestore_customer_credit_scope label{ font-size: 15px; display: inline-block; font-weight: bold }
    #magestore_customer_credit_scope select{ display: inline-block; width: 50%; }
    #magestore_customer_credit_scope .product-review{ margin-left: 148px; }
    #magestore_customer_credit_scope #credit_amount_range{ max-width: 135px; height: 25px; font-size: 14px; }
    #magestore_customer_credit_scope .credit_type_range_div{ float: left;width: 100%; }
</style>
<?php
/**
 * @var $block Magestore\Customercredit\Block\Product\View
 */
$store = $block->getStore();
$_product = $block->getProduct();
$_creditAmount = $block->getCreditAmount($_product);
$_formData = $block->getFormConfigData();
$includeTax = ( $block->getTaxHelper()->getPriceDisplayType() != 1 );
$rateTax = $block->getCatalogHelper()->getTaxPrice($_product, 100, $includeTax) / 100;

$credit_amount_range_current = ($_formData->getAmount() ?
    $_formData->getAmount()
    : (array_key_exists('from', $_creditAmount) ? $_creditAmount['from'] : 0)
) ;
?>
<div class="price-box">
    <span class="regular-price">
        <span class="price" id="storecredit-product-value">
            &nbsp;
        </span>
    </span>
</div>
<input type="hidden" name="credit_price_amount" id="credit_price_amount" value="0"/>

<div class="customercredit-product-info">
    <div id="magestore_customer_credit_scope">
        <?php if ($_creditAmount['type'] == 'range'): ?>
            <div id="magestore_customer_credit_scope">
                <div class="credit_type_range_div">
                    <p>
                        <label class="required" for="amount">
                            <?= /* @noEscape */ __('Enter Credit Value: ') ?>
                        </label>&nbsp;
                        <input id="credit_amount_range"
                               name="amount"
                               class="input-text required-entry validate-greater-than-zero"
                               value="<?= /* @noEscape */ $credit_amount_range_current ?>" />
                    </p>
                    <div class="product-review">
                        (<span class="price">
                            <?= /* @noEscape */ $_creditAmount['from_txt'] ?>
                        </span> -  <span class="price">
                            <?= /* @noEscape */ $_creditAmount['to_txt'] ?>
                        </span>)
                    </div>
                </div>
            </div>
        <?php elseif ($_creditAmount['type'] == 'dropdown'): ?>
            <div id="magestore_customer_credit_scope">
                <p>
                    <label for="amount"><?= /* @noEscape */ __('Select Credit Value:') ?></label>
                    <select id="credit_amount_dropdown" name="amount" class="required-entry select">
                        <?php $options = array_combine($_creditAmount['options'], $_creditAmount['options_txt']) ?>
                        <?php foreach ($options as $value => $label): ?>
                            <option value="<?= /* @noEscape */ $value ?>"
                                <?php if ($value == $_formData->getAmount()) {echo 'selected';} ?> >
                                <?= /* @noEscape */ $label ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </p>
            </div>
        <?php elseif ($_creditAmount['type'] == 'static'): ?>
            <div id="magestore_customer_credit_scope">
                <p>
                    <label class="required" for="amount"><?= /* @noEscape */ __('Store Credit value:') ?></label>
                    <?= /* @noEscape */
                        __('<span class="regular-price">%1</span>', '&nbsp;'.$_creditAmount['value_txt']) ?>
                    <input type="hidden" name="amount" value="<?= /* @noEscape */ $_creditAmount['value'] ?>" />
                </p>
            </div>
        <?php elseif ($_creditAmount['type'] == 'any'): ?>
            <div id="magestore_customer_credit_scope">
                <p>
                    <label for="amount"><?= /* @noEscape */ __('Enter Amount:') ?></label>
                    <input id="amount"
                           name="amount"
                           class="credit_type_any_amount input-text required-entry validate-greater-than-zero"
                           value="<?= /* @noEscape */ $_formData->getAmount() ?>" />
                </p>
                <p><?= /* @noEscape */ __('Credit Rate: ') . $_product->getStorecreditRate() ;?></p>
                <?= /* @noEscape */ __('Credit Value: ') ?>
                <span class="value"
                      class="credit_type_any_value"
                      id="value">
                    <?= /* @noEscape */ $_product->getStorecreditValue(); ?>
                </span>
            </div>
        <?php endif ?>

    </div>

    <script type="text/x-magento-init">
        {
            "#magestore_customer_credit_scope": {
                "productCredit": {
                    "type": "<?= /* @noEscape */
                        array_key_exists('type', $_creditAmount) ? $_creditAmount['type'] : '0' ?>",
                    "storecredit_rate": <?= /* @noEscape */
                        array_key_exists('storecredit_rate', $_creditAmount) ?
                            $_creditAmount['storecredit_rate'] : 0 ?>,
                    "rate_tax": <?= /* @noEscape */ $rateTax ? $rateTax : 0 ?>,
                    "from": <?= /* @noEscape */
                        array_key_exists('from', $_creditAmount) ? $_creditAmount['from'] : 0  ?>,
                    "to": <?= /* @noEscape */
                        array_key_exists('to', $_creditAmount) ? $_creditAmount['to'] : 0 ?>,
                    "priceFormatJs": <?= /* @noEscape */ $block->getPriceFormatJs() ?>,
                    "credit_amount_min": <?= /* @noEscape */
                        array_key_exists('from', $_creditAmount) ? $_creditAmount['from'] : 0 ?>,
                    "credit_amount_max": <?= /* @noEscape */
                        array_key_exists('to', $_creditAmount)  ? $_creditAmount['to'] : 0 ?>,
                    "priceFormat": "<?= /* @noEscape */
                        $store->getCurrentCurrency()->format(1000, [], false); ?>",
                    "prices": <?= /* @noEscape */
                        array_key_exists('prices', $_creditAmount) ? json_encode($_creditAmount['prices']) : '{}' ?>,
                    "price": <?= /* @noEscape */
                        array_key_exists('price', $_creditAmount) ? $_creditAmount['price'] : 0 ?>,
                    "amount": <?= /* @noEscape */ $_formData->getAmount() ? $_formData->getAmount() : 0 ?>,
                    "rate": <?= /* @noEscape */ $_product->getStorecreditRate() ? $_product->getStorecreditRate() : 0 ?>
                }
            }
        }
    </script>


    <?php if ($block->allowSendCredit()): ?>
        <div id="send_credit_to_friend_form">
            <p class="customercredit-send-friend">
                <input type="checkbox"
                       value="1"
                       name="send_friend"
                       id="send_friend" <?php if ($_formData->getSendFriend()) {echo 'checked';} ?> />
                <label for="send_friend"><?= /* @noEscape */ __('Send credit to friend') ?></label>
            </p>

            <div class="customercredit-receiver"
                 id="customercredit-receiver"
                 style="<?php if (!$_formData->getSendFriend()) {echo 'display:none;';} ?>">
                <fieldset class="fieldset product-credit"
                          data-hasrequired="<?= /* @noEscape */ __('* Required Fields') ?>">
                    <div class="field sender">
                        <label for="customer_name"><?= /* @noEscape */ __('Sender name (optional)') ?></label><br/>
                        <input type="text"
                               class="input-text"
                               name="customer_name"
                               id="customer_name"
                               value="<?= /* @noEscape */ $_formData->getCustomerName() ?>"
                               maxlength="30"/>
                    </div>
                    <div class="field recipient_name required">
                        <label class="label" for="recipient_name">
                            <?= /* @noEscape */ __('Recipient name') ?>
                        </label><br/>
                        <input type="text"
                               class="input-text required-entry"
                               name="recipient_name"
                               id="recipient_name"
                               value="<?= /* @noEscape */ $_formData->getRecipientName() ?>"
                               maxlength="30"/>
                    </div>
                    <div class="field recipient_email required">
                        <label class="label" for="recipient_email">
                            <?= /* @noEscape */ __('Recipient email address') ?>
                        </label><br/>
                        <input type="text"
                               class="input-text required-entry validate-email validate-same-email"
                               name="recipient_email"
                               id="recipient_email"
                               value="<?= /* @noEscape */ $_formData->getRecipientEmail() ?>"/>
                    </div>
                    <label class="message" for="message"><?= /* @noEscape */ __('Custom message') ?></label><br/>
                    <textarea name="message"
                              id="message"
                              class="">
                        <?= /* @noEscape */ $_formData->getMessage() ?>
                    </textarea><br/>
                </fieldset>
            </div>
        </div>

        <script type="text/x-magento-init">
        {
            "#send_credit_to_friend_form": {
                "sendCreditToFriend": {}
            }
        }
    </script>
    <?php endif; ?>
</div>
