<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

if ($block->isZendBarcodeInstalled()):
    $barcode = "";
    $barcodes = $block->getBarcodes();
    $config = $block->getTemplateData();

    if (count($barcodes) > 0):
        $qty = count($barcodes);
        $label_per_row = (int)($config['label_per_row']);
        $maxRowNumber = ceil($qty / $label_per_row);
        $measurement_unit = $config['measurement_unit'];
        $paper_height = $config['paper_height'] . $measurement_unit;
        $paper_width = $config['paper_width'] . $measurement_unit;
        $label_height = $config['label_height'] . $measurement_unit;
        $label_width = $config['label_width'] . $measurement_unit;
        $margin_left = $config['left_margin'] . $measurement_unit;
        $margin_right = $config['right_margin'] . $measurement_unit;
        $margin_bottom = $config['bottom_margin'] . $measurement_unit;
        $margin_top = $config['top_margin'] . $measurement_unit;
        $jewelryWidth = (($config['label_width'] + $config['left_margin'] + $config['right_margin'])) * 2;
        $jewelryMarginLeft = ($config['paper_width'] - $jewelryWidth);

        /* barcode attributes */
        $font_size = $config['font_size'] . 'px';
        $attributes_height_label = ($config['paper_height'] - $config['label_height']) - $config['top_margin']
            - $config['bottom_margin'] - 1;
        /* end - barcoder attributes */

        $bodyHeight = $maxRowNumber * (int)($paper_height);
        if ($maxRowNumber > 0):
            $generated = 0;
            for ($rowNumber = 1; $rowNumber <= $maxRowNumber; $rowNumber++):
                ?>
                <div class="barcode-row <?php if ($block->isJewelry()) {echo " jewelry ";} ?>"
                     style="text-align: center;">
                    <?php
                    for ($labelInRow = 1; $labelInRow <= $label_per_row; $labelInRow++) {
                        if ($qty > 0) {
                            $qty--;
                            if (isset($barcodes[$generated])) {
                                $source = $barcodes[$generated];
                                $attributes_soucre = $barcodes[$generated]['attribute_data'];
                                $source = $barcodes[$generated]['barcode_source'];
                                // phpcs:ignore Magento2.Functions.DiscouragedFunction
                                ob_start();
                                // phpcs:ignore Magento2.Functions.DiscouragedFunction
                                imagepng($source->draw());
                                // phpcs:ignore Magento2.Functions.DiscouragedFunction
                                $barcode = ob_get_contents();
                                // phpcs:ignore Magento2.Functions.DiscouragedFunction
                                ob_end_clean();
                                ?>
                                <?php if (!$block->isJewelry()): ?>
                                    <div class="barcode-att">
                                        <div class="barcode-att"
                                             style=" height:<?= /* @noEscape */ $attributes_height_label
                                                . $measurement_unit ?>;
                                                     line-height:<?= /* @noEscape */ ($attributes_height_label
                                                        / (($attributes_soucre) ? count($attributes_soucre) : 1))
                                                                 . $measurement_unit ?>
                                                     ">
                                            <?php
                                            if ($attributes_soucre) {
                                                foreach ($attributes_soucre as $value) {
                                                    if ($value) {
                                                        ?>
                                                        <span class='barcode-att barcode-att-cal'
                                                              style="font-size :<?= /* @noEscape */ $font_size ?>"><?=
                                                            /* @noEscape */ $value; ?></span></br>
                                                        <?php
                                                    }
                                                }
                                            }
                                            ?>
                                        </div>
                                        <div class="barcode-att">
                                            <img class='barcode-img' name='barcode'
                                                 src="data:image/png;base64,<?=
                                                 /* @noEscape */ base64_encode($barcode); ?>"/>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php if ($block->isJewelry()): ?>
                                    <div class="jewelry-container">
                                        <div class="jewelry-tongue"></div>
                                        <img class='barcode-img' name='barcode'
                                             src="data:image/png;base64,<?=
                                             /* @noEscape */ base64_encode($barcode); ?>"/>
                                        <img class='barcode-img' name='barcode'
                                             src="data:image/png;base64,<?=
                                             /* @noEscape */ base64_encode($barcode); ?>"/>
                                    </div>
                                <?php endif;
                                $generated++;
                            }
                        }
                    }
                    ?>
                </div>
                <div class="clear"></div>
                <?php
            endfor;
        endif;
        ?>
        <style type="text/css">
            body, html {
                height: <?= /* @noEscape */ $bodyHeight.$measurement_unit;?>;
                margin: 0px;
            }

            .barcode-row {
                height: <?= /* @noEscape */ $paper_height;?>;
                width: <?= /* @noEscape */ $paper_width;?>;
                display: inline-flex;
            }

            .barcode-row .barcode-img {
                height: <?= /* @noEscape */ $label_height;?>;
                width: <?= /* @noEscape */ $label_width;?>;
                margin-top: <?= /* @noEscape */ $margin_top;?>;
                margin-bottom: <?= /* @noEscape */ $margin_bottom;?>;
                margin-left: <?= /* @noEscape */ $margin_left;?>;
                margin-right: <?= /* @noEscape */ $margin_right;?>;
                float: left;
            }

            .barcode-row.jewelry .jewelry-container {
                width: <?= /* @noEscape */ $jewelryWidth.$measurement_unit;?>;
                height: 100%;
                float: right;
            }

            .barcode_preview_container .barcode-row.jewelry .jewelry-container .jewelry-tongue {
                right: -<?= /* @noEscape */ $jewelryMarginLeft.$measurement_unit;?>;
                width: <?= /* @noEscape */ $jewelryMarginLeft.$measurement_unit;?>;
            }

            .barcode-row.jewelry .jewelry-container .barcode {
                height: 100%;
            }

            @media print {
                body {
                    color: #000;
                    background-color: #fff;
                }
            }

            @page {
                size: auto;
                margin: 2mm 4mm;
            }

            .clear {
                clear: both
            }
        </style>
    <?php endif;
    else:?>
    <div style="color: red"><?= /* @noEscape */ __('Unable to Preview Barcode. Require ') . '<a href="'
        . $block->getBarcodeSetupGuideUrl() . '">Zend_Barcode.</a>' ?></div>
<?php endif; ?>
