<div id="purchase_email_header_block" class="purchase_email"
     data-modal-info="<?php /* @escapeNotVerified */ echo $block->getWidgetOptions();?>">
    <div class="admin__page-section-item email-header">
        <table class="data-table admin__table-secondary email-header-table" style="font-size: 13px">
            <tr class="col-0">
                <td class="label" style="width: 32%">
                    <strong><?php echo __('Return From') ?></strong>
                </td>
                <td class="label" style="width: 32%">
                    <strong><?php echo __('Delivery To') ?></strong>
                </td>
                <td class="label" style="width: 32%">
                    <strong><?php echo __('Return Request') ?></strong>
                </td>
            </tr>
            <tr class="col-1">
                <td valign="top">
                    <?php echo $block->getDataHtmlWarehouse('name') ?>
                    <?php echo $block->getDataHtmlWarehouse('street') ?>
                    <?php echo $groupAddress = $block->getCityRegionPostCodeWarehouse(); ?>
                    <?php echo $block->getCountryWarehouse() ?>
                    <span><?php echo __('Telephone: ') ?></span>
                    <span><?php echo $block->getWarehouseData('phone') ?></span><br/>
                    <span><?php echo __('Email: ') ?></span>
                    <?php echo $block->getDataHtmlWarehouse('email') ?>
                </td>
                <td class="label" valign="top">
                    <?php echo $block->getDataHtml('supplier_name') ?>
                    <?php echo $block->getDataHtml('street') ?>
                    <?php echo $groupAddress = $block->getCityRegionPostCode(); ?>
                    <?php echo $block->getCountry() ?>
                    <span><?php echo __('Telephone: ') ?></span>
                    <span><?php echo $block->getSupplierData('telephone') ?></span><br/>
                    <span><?php echo __('Email: ') ?></span>
                    <?php echo $block->getDataHtml('contact_email') ?>
                </td>
                <td valign="top">
                    <span><?php echo __('R.E#: ') ?></span>
                    <span><?php echo $block->getReturnOrderCode() ?></span><br/>
                    <span><?php echo __('Created At: ') ?></span>
                    <span><?php echo $block->getReturnDate() ?></span><br/>
                    <span><?php echo __('Status: ') ?></span>
                    <span><?php echo $block->getReturnOrderStatus() ?></span><br/>
                </td>
            </tr>
        </table>
    </div>
</div>
<style type="text/css">
    * {
        background: transparent !important;
        color: #000 !important;
        box-shadow: none !important;
        text-shadow: none !important;
        filter: none !important;
        -ms-filter: none !important;
    }
    @media print
    {
        @page { margin: 0; }
        body  { margin: 1.6cm; }
    }
</style>