<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Multi */ ?>
<?php

?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<?php $notifyBlock = $block->getLayout()->createBlock('Mageants\OutofStockNotification\Block\Product\Notify');?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label" for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
            <input type="hidden"
                   name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                   value="<?= /* @escapeNotVerified */ $_selections[0]->getSelectionId() ?>"/>
        <?php else: ?>
            <select multiple="multiple"
                    size="5"
                    id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>"
                    name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>][]"
                    data-selector="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>][]"
                    class="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?> multiselect product bundle option change-container-classname"
                    <?php if ($_option->getRequired()) echo 'data-validate={required:true}' ?>>
                <?php if(!$_option->getRequired()): ?>
                    <option value=""><?= /* @escapeNotVerified */ __('None') ?></option>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>"
                            <?php if ($block->isSelected($_selection)) echo ' selected="selected"' ?>
                            <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>>
                        <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>

            <!-- Out of Stock Notification Start -->
            <?php foreach ($_selections as $_selection): ?>
              <?php 
                $_selectionProduct = $notifyBlock->getProductStock($_selection->getId()); 
                      $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                      $inventory = $objectManager->create('\Magento\CatalogInventory\Model\Stock\StockItemRepository');
                      $stockInventor =$inventory->get($_selection->getId());
              ?>
              <?php if ((!$stockInventor->getIsInStock()) && $notifyBlock->isAllowCustomerGroup() == 1 && $_selection->getIsEnableOutofstock()): ?>
                <div id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>" class="mageants-bundle-option" style="display: none;">
                  <div class="mageants-notify-main">
                    <div id="mageants-notify-form">
                      <div class="mageants-notify-bundle">
                        <div>
                          <p><?php echo $notifyBlock->getNotificationMessage(); ?></p>
                          <input type="hidden" id="customerId" name="customerId" value="<?php echo $notifyBlock->getLoggedCustomerId(); ?>">
                          <input type="hidden" id="productSku" name="productSku" value="<?php echo $_selection->getSku(); ?>">
                          <input type="hidden" id="productName" name="productName" value="<?php echo $_selection->getName(); ?>">
                          <input type="hidden" name="producturl" class="producturl" value="<?php echo $block->getProduct()->getUrlKey().'.html'; ?>" />
                        </div>
                        <div>
                          <div>
                            <input type="email" id="notify" name="notify" placeholder="<?= __('Please enter your email id') ?>" value = "<?php if ($notifyBlock->isLoggedIn()) { echo trim($notifyBlock->getLoggedCustomerEmail()); } ?>">
                          </div>
                          <div style="margin-top: 10px;">
                            <button id="notifyButton" class="action primary notifyBundle" formaction="<?php echo $notifyBlock->getSaveUrl(); ?>" title="<?= __('Notify') ?>"><?= __('Notify') ?></button>
                          </div>
                        </div>                                
                      </div>
                    </div>
                  </div>
                </div>
              <?php endif; ?>
            <?php endforeach; ?>
            <!-- Out of Stock Notification End -->
        <?php endif; ?>
    </div>
</div>
