<?php
/**
 * Copyright © 2017 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magestore\Giftvoucher\Pricing\Render\FinalPriceBox $block */
$_product = $block->getSaleableItem();

$giftAmount = $_product->getPriceModel()->getGiftAmount($_product);

/** @var \Magento\Catalog\Pricing\Price\RegularPrice $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Catalog\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');

$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if ($block->getRequest()->getFullActionName() != 'catalog_product_view'
        && $block->getRequest()->getFullActionName() != 'checkout_cart_configure'
        && $block->getRequest()->getFullActionName() != 'wishlist_index_configure'): ?>
    <?php if ($giftAmount['price_type'] == 1): ?>
        <?php if ($block->hasSpecialPrice()): ?>
            <span class="special-price">
                <?php echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label'     => __('Special Price'),
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </span>
            <span class="old-price">
                <?php echo $block->renderAmount($priceModel->getAmount(), [
                    'display_label'     => __('Regular Price'),
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
        <?php else: ?>
            <?php echo $block->renderAmount($finalPriceModel->getAmount(), [
                'price_id'          => 'product-giftcard-price',
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        <?php endif; ?>

        <?php if ($block->showMinimalPrice()): ?>
            <?php if ($block->getUseLinkForAsLowAs()):?>
                <a href="<?php echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
                    <?php echo $block->renderAmountMinimal(); ?>
                </a>
            <?php else:?>
                <span class="minimal-price-link">
                    <?php echo $block->renderAmountMinimal(); ?>
                </span>
            <?php endif?>
        <?php endif; ?>
    <?php else: ?>
        <div class="price-box">
            <p class="min-price">
                <span class="price-label"><?php echo __('From')?></span>
                <?php echo $block->renderAmount($block->getMinimalGiftPrice(), [
                    'price_id'          => $block->getPriceId('product-from-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </p>
            <p class="max-price">
                <span class="price-label"><?php echo __('To')?></span>
                <?php echo $block->renderAmount($block->getMaximalGiftPrice(), [
                    'price_id'          => $block->getPriceId('product-to-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </p>
        </div>
    <?php endif; ?>
    <script>
//        require([
//            "jquery",
//            "jquery/ui",
//            "mage/mage",
//            "mage/backend/form",
//            "mage/validation"
//        ], function(jQuery){
//            jQuery('[data-product-id="<?php echo $_product->getId();?>"]').parent().find('.towishlist')
//                    .on('click', function(event) {
//                params = jQuery('[data-product-id="<?php echo $_product->getId();?>"]').parent().find('.towishlist').data('post'),
//                data = <?php echo $_product->getPriceModel()->setDefaultValues($_product) ?>;
//                params.data = jQuery.extend(true, {}, params.data,data);
//                jQuery('[data-product-id="<?php echo $_product->getId();?>"]').parent().find('.towishlist').data('post', params);
//            })
//        });
    </script>
<?php else: ?>
    <span class="price-box">
        <?php echo $block->renderAmount($block->getDefaultGiftPrice(), [
            'price_id'          => 'product-giftcard-price',
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
<?php endif; ?>
