<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var $block \Magestore\FulfilReport\Block\Adminhtml\Report\Navigation */ ?>
<?php $staffReports = $block->getStaffReportList() ?>
<?php $warehouseReports = $block->getWarehouseReportList() ?>
<?php $isMSIEnable = $block->isMSIEnable() ?>
<div class="fulfil-report">
    <div class="wrap-report">
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo __('Staff Report') ?></div>
            <div class="panel-body">
                <div class="row">
                    <?php foreach ($staffReports as $report => $name): ?>
                        <?php $reportLink = $block->getReportLink($report) ?>
                        <div class="col-sm-3">
                            <div class="item-staff">
                                <a class="actions" href="<?php echo $reportLink ?>"
                                   title="<?php __('Fulfilment by Staff') ?>">
                                    <span class="<?php echo 'icon-icon-Back-end-' . $report ?>"></span>
                                    <label><?php echo $name ?></label>
                                </a>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo __('Warehouse Report') ?></div>
            <div class="panel-body">
                <div class="row">
                    <?php foreach ($warehouseReports as $report => $name): ?>
                        <?php $reportLink = $block->getReportLink($report) ?>
                        <div class="col-sm-3">
                            <div class="item-staff">
                                <a class="actions" href="<?php echo $reportLink ?>"
                                   title="<?php __('Fulfilment by %1', $isMSIEnable ? "Source" : "Warehouse") ?>">
                                    <span class="<?php echo 'icon-icon-Back-end-' . $report ?>"></span>
                                    <label><?php echo $name ?></label>
                                </a>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
</div>
