<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */ /** @var Magestore\FulfilReport\Block\Adminhtml\Report\Verify $block */ ?>

<?php
$verifiedOrdersPerDay = $block->getVerifyRequestCollectionPerDay();
$dayRange = "'" . implode("','", array_keys($verifiedOrdersPerDay)) . "'";
$verifiedOrdersRange = implode(", ", $verifiedOrdersPerDay);
?>
<script type="text/javascript">
    require([
        "jquery",
        "jquery/ui",
        "Magestore_FulfilReport/js/chart/highcharts",
        "Magestore_FulfilReport/js/chart/data",
        "Magestore_FulfilReport/js/chart/exporting"
    ], function ($) {
        // Create the chart
        Highcharts.chart('container-verify', {
            chart: {
                type: 'line'
            },
            title: {
                text: 'Report verified orders by day'
            },
            xAxis: {
                categories:  [<?php echo $dayRange ?>]
            },
            yAxis: {
                title: {
                    text: 'Number Of Verified Orders'
                }
            },
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    },
                    enableMouseTracking: false
                }
            },
            series: [{
                name: 'Number Of Verified Orders',
                data: [<?php echo $verifiedOrdersRange ?> ]
            }]
        });
    });
</script>

