<div id="purchase_sumary_total_block" class="import-product" 
     data-modal-info="<?php /* @escapeNotVerified */ echo $block->getWidgetOptions();?>">
    <div class="admin__page-section-item order-totals">
        <div class="admin__page-section-item-title">
            <span class="title"><?php echo __('Invoice Totals') ?></span>
        </div>
        <table class="data-table admin__table-secondary order-subtotal-table">
            <tfoot>
                <tr class="col-0">
                    <td class="label">
                        <strong><?php echo __('Grand Total (incl. Tax)') ?></strong>
                    </td>
                    <td>
                        <strong><?php echo $block->getPriceFormat('grand_total_incl_tax'); ?></strong>
                    </td>
                </tr>
                <tr class="col-1">
                    <td class="label">
                        <strong><?php echo __('Total Due') ?></strong>
                    </td>
                    <td>
                        <strong><?php echo $block->getPriceFormat('total_due'); ?></strong>
                    </td>
                </tr>
                <?php $totalRefund = $block->getPrice('total_refund'); ?>
                <?php if($totalRefund>0): ?>
                    <tr class="col-3">
                        <td class="label">
                            <strong><?php echo __('Total Refund') ?></strong>
                        </td>
                        <td>
                            <strong><?php echo $block->getPriceFormat('total_refund') ?></strong>
                        </td>
                    </tr>
                <?php endif; ?>
            </tfoot>

            <tbody>
                <tr class="col-0">
                    <td class="label">
                        <strong><?php echo __('Grand Total (excl. Tax)') ?></strong>
                    </td>
                    <td>
                        <strong><?php echo $block->getPriceFormat('grand_total_excl_tax'); ?></strong>
                    </td>
                </tr>
                <tr class="col-2">
                    <td class="label"><?php echo __('Discount') ?></td>
                    <td>
                        <span><?php echo $block->getPriceFormat('total_discount'); ?></span>
                    </td>
                </tr>
                <tr class="col-3">
                    <td class="label"><?php echo __('Tax') ?></td>
                    <td>
                        <span><?php echo $block->getPriceFormat('total_tax'); ?></span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>