<?php
/**
 * @category Mageants GiftCertificate
 * @package Mageants_GiftCertificate
 * @copyright Copyright (c) 2016 Mageants
 * @author Mageants Team <support@mageants.com>
 */
?>

<div id="cart-totals" class="cart-totals" data-bind="scope:'block-totals'">
	<script type="text/x-magento-init">
            {
                "#cart-totals": {
                    "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                }
            }
    </script>
</div>
