<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */ /** @var \Magestore\DropshipSuccess\Block\Supplier\Layout\Welcome $block */ ?>
<header class="page-header">
    <div class="panel wrapper">
        <div class="panel header">
            <a class="action skip contentarea" href="#contentarea"><span>Skip to Content</span></a>
            <ul class="header links">
                <li class="greet welcome">
                    <span><?php echo $block->getWelcomeMessage() ?></span>
                </li>

            </ul>
        </div>
    </div>
</header>