<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php //$_order = $block->getOrder() ?>

<div id="order-messages">
    <?php echo $block->getChildHtml('order_messages') ?>
</div>
<?php echo $block->getChildHtml('order_info') ?>
<?php echo $block->getChildHtml('supplier_info') ?>
<?php echo $block->getChildHtml('dropship_request_items') ?>