<tr>
    <td class="label">
        <label>
            <span><?php echo __('Installation guide')?></span>
        </label>
    </td>
    <td class="value barcode-installation-guide">
        <h4 class="title"><?php echo __('Install the required module')?></h4>
        <ul class="barcode-installation-module-guide">
            <li>
                <?php echo __('If you can access to your server via SSH:');?><br />
                <div class="guide-content">
                    <?php echo __('Use cd command to your Magento root folder. After that, enter the commands:');?>
                    <br />
                    <br />
                    <b>composer require zendframework/zend-barcode</b>
                    <br />
                    <br />
                    <a href="https://docs.zendframework.com/zend-barcode/"><?php echo __('View detail')?></a>
                </div>
            </li>
        </ul>
    </td>
    <td class=""></td>
</tr>

<style type="text/css">
    .barcode-installation-guide h4.title{
        padding-top:7px;
        padding-left:0px;
        margin-top:0px;
        margin-left:0px;
        font-size: 14px;
        font-weight: 600;
    }
    .barcode-installation-guide ul li{
        list-style: none;
        margin: 5px 0px;
    }
    .barcode-installation-guide ol li{
        list-style: inherit;
    }
    .barcode-installation-guide li .guide-content{
        padding-left: 20px;
    }
</style>
