<?php
/**
 * @category Mageants MaintenanceMode
 * @package Mageants_MaintenanceMode
 * @copyright Copyright (c) 2019 Mageants
 * @author Mageants Team <support@mageants.com>
 */
?>
<div id="mageants-notice-msg">
    <?= /* @noEscape */ $block->checkRegister() ?>
</div>

<div id="mageants-background">
    <!--Multiple Image Background-->
    <?php if ($block->getBackgroundType() === 'multiple_images'
        && $block->getListImagesUrl()) : ?>
        <?php $listImagesUrl = implode(',', $block->getListImagesUrl()) ?>
        <style>
            #mageants-background {
                background: no-repeat center center fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
                transition-delay: 2s;
            }   
        </style>
        <script>
            require([
                'jquery'
            ], function ($) {
                var images    = '<?= /* @noEscape */ $listImagesUrl ?>';
                images        = images.split(',');
                var nextImage = 0;
                doSlideShow();

                function doSlideShow () {
                    if (nextImage >= images.length) {
                        nextImage = 0;
                    }
                    $('#mageants-background')
                    .fadeIn('slow', function () {
                        setTimeout(doSlideShow, 5000);
                    }).css('background-image', 'url("' + images[nextImage++] + '")');
                }
            });
        </script>
    <?php endif; ?>

    <!--Single Image Background-->
    <?php if ($block->getBackgroundType() === 'image') : ?>
        <style>
            #mageants-background {
                background: url("<?= /* @noEscape */ $block->getBgImageUrl() ?>") no-repeat center center fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
            }
        </style>
    <?php endif; ?>

    <!--Video Background-->
    <?php if ($block->getBackgroundType() === 'video'
        && $block->getBgVideoUrl()) : ?>
        <video autoplay muted loop id="mageants-video">
            <source src="<?= $block->escapeHtmlAttr($block->getBgVideoUrl()) ?>"
                    type="video/mp4">
        </video>
    <?php endif; ?>
</div>
