<?php
/**
 * Copyright © 2017 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

$_product = $block->getProduct(); ?>
<?php if ($_product->getTypeId() == 'giftvoucher' && $block->contentCondition()) : ?>
    <div onmouseout="hiddenGiftcardDescription()" onmouseover="showGiftcardDescription()">
        <a id="giftvoucher-view-condition" ><?php echo __('View usage conditions of this Gift Card') ?></a>
        <div id="giftvoucher-tooltip" style="display:none;">
            <?php echo $block->contentCondition() ?>
        </div>
    </div>    
<?php endif; ?>
<script>
    require([
        "jquery"
    ], function ($) {
        showGiftcardDescription = function () {
            $('#giftvoucher-tooltip').show();
        };
        hiddenGiftcardDescription = function () {
            $('#giftvoucher-tooltip').hide();
        }
    })
</script>