<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->get(\Magento\Customer\Model\SessionFactory::class);
// $this->_customerSession = $customerSession->create();
$customerSession->create();

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(\Magento\Catalog\Helper\Output::class); //@codingStandardsIgnoreLine
// $_helper = $block->getData('outputHelper');
$notifyBlock = $block->getLayout()->createBlock(\Mageants\OutofStockNotification\Block\Product\Notify::class);
//@codingStandardsIgnoreStart
$_stockHelper = $this->helper(\Mageants\OutofStockNotification\Helper\Data::class);
//@codingStandardsIgnoreEnd
$enableNotification = 0;

// get product lable block

?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $block->escapeHtml('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */  $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php
                    $notifyBlock->setListProduct($_product->getId());
                    $enableNotification = $_product->getIsEnableOutofstock();
                    
                ?>
                <?= /* @noEscape */  ($iterator++ == 1) ?
                '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @noEscape */  $_product->getProductUrl() ?>"
                        class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @noEscape */  $_product->getProductUrl() ?>">
                                <?= /* @noEscape */  $_helper->productAttribute(
                                    $_product,
                                    $_product->getName(),
                                    'name'
                                ) ?>
                            </a>
                        </strong>
                        <?= /* @noEscape */  $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>


                        <div class="product-item-inner">

                        <!-- Out of Stock Notification Start -->
                        
                        <?php if ($notifyBlock->isEnable() &&
                        $notifyBlock->isAllowCustomerGroup() == 1 &&
                        $notifyBlock->isShowNotifyOnCategory() == "1"
                        ):?>
                            
                            <?php

                            if (!$_product->isSaleable() &&
                                $enableNotification != 0 &&
                            $_product->getTypeId() != "configurable" &&
                            ($_product->getTypeId() != "bundle" ||
                            ($_product->getTypeId() == "bundle" &&
                            $notifyBlock->getAllowSelectSimpleBundle() == 1))
                            ):?>
                                <div class="mageants-notify-main">
                                    <div id="mageants-notify-form">
                                        <form action="#">
                                            <div>
                                                <p><?= /* @noEscape */ $notifyBlock->getNotificationMessage(); ?></p>
                                            </div>
                                            <div class="mageants-stock-notification">
                                                <input type="email" class="notifyEmail" name="notify"
                                                value = "<?php if ($notifyBlock->isLoggedIn()) {//@codingStandardsIgnoreStart
                                                            echo trim($notifyBlock->getLoggedCustomerEmail()); } //@codingStandardsIgnoreEnd?>"
                                                placeholder="<?= $block->escapeHtml('Please enter your email id') ?>">
                                                <input type="hidden"  class="customerId"
                                                value="<?= /* @noEscape */ $_stockHelper->getCustomerId(); ?>" />
                                                <input type="hidden"  class="productSku"
                                                value="<?= /* @noEscape */ $_product->getSku(); ?>" />
                                                <input type="hidden"  class="productName"
                                                value="<?= /* @noEscape */ $_product->getName(); ?>" />
                                                <input type="hidden" name="producturl" class="producturl"
                                                value="<?= /* @noEscape */ $_product->getUrlKey().'.html'; ?>">
                                                <button class="action primary notify-button" type="button"
                                                title="<?= $block->escapeHtml('Notify') ?>"
                                                    style="margin-top: 10px;"><?= $block->escapeHtml('Notify') ?>
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            <?php endif;?>
                            <?php if ($_product->getTypeId() == "configurable"):
                                $data = $_product->getTypeInstance()->getConfigurableOptions($_product);
                                $optionsData = $_product->getTypeInstance(true)->
                                getConfigurableAttributesAsArray($_product);
                                $superAttrCode=[];
                                foreach ($optionsData as $option) {
                                    $superAttrCode[]=$option['attribute_code'];
                                }
                                $usedProducts = $_product->getTypeInstance()->getUsedProductCollection($_product);
                                foreach ($usedProducts as $childProduct) {
                                    $stockProduct = $notifyBlock->getProductStock($childProduct->getId());
                                    $simpleProduct = $notifyBlock->getProduct($childProduct->getId());
                                   
                                    $id = "";
                                    foreach ($superAttrCode as $key => $value) {
                                            $id = $id.$simpleProduct->getData($value);
                                    }
                                    if (!$childProduct->isSaleable() &&
                                        $simpleProduct->getIsEnableOutofstock() == 1 &&
                                        $notifyBlock->isAllowCustomerGroup()
                                    ) {
                                        ?>  
                                    <div class="mageants-notify-main">
                                        <div id="mageants-notify-form-simple">
                                            <div id= "<?= /* @noEscape */ $id; ?>" class="mageants-notify-conf"
                                                style="display: none;">
                                                <div>
                                                    <p><?= /* @noEscape */ $notifyBlock->getNotificationMessage(); ?>
                                                    </p>
                                                 
                                                </div>
                                                <div>
                                                    
                                                    <div>
                                                        <input type="email" class="notifyEmail" name="notify"
                                                        placeholder="<?= $block->
                                                        escapeHtml('Please enter your email id') ?>"
                                                        value = "<?php if ($notifyBlock->isLoggedIn()) {//@codingStandardsIgnoreStart
                                                            echo trim($notifyBlock->getLoggedCustomerEmail()); } //@codingStandardsIgnoreEnd?>">
                                                           <input type="hidden" class="customerId" name="customerId"
                                                    value="<?= /* @noEscape */ $notifyBlock->getLoggedCustomerId(); ?>">
                                                            <input type="hidden" class="productSku" name="productSku"
                                                            value="<?= /* @noEscape */ $simpleProduct->getSku(); ?>">
                                                            <input type="hidden" class="productName" name="productName"
                                                            value="<?= /* @noEscape */ $simpleProduct->getName(); ?>">
                                                            <input type="hidden" name="producturl" class="producturl"
                                                        value="<?= /* @noEscape */ $_product->getUrlKey().'.html'; ?>">
                                                        <button
                                                        id="<?= /* @noEscape */ "swatch-opt-".$_product->getId(); ?>"
                                                            class="action primary notify-button" type="submit"
                                                            title="<?= $block->escapeHtml('Notify') ?>">
                                                            <?= $block->escapeHtml('Notify') ?></button>
                                                        <style type="text/css">
                                                            
                                                            .notify-button{ margin-top: 10px; margin-bottom:10px;}
                                                        </style>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                        <?php
                                    }
                                }
                            endif;?> 
                        <?php endif;?>
                        
                        <!-- Out of Stock Notification End -->
                        <?php if ($_product->getTypeId() != 'bundle'): ?>
                            <div class="product actions product-item-actions"
                            <?= /* @noEscape */ strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= /* @noEscape */ strpos($pos, $viewMode . '-primary') ?
                                $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                        data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                            action="<?= /* @noEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product"
                                            value="<?= /* @noEscape */ $postParams['data']['product'] //@codingStandardsIgnoreStart?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                            value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] //@codingStandardsIgnoreEnd?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= $block->escapeHtml('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available">
                                                <span><?= $block->escapeHtml('In stock') ?></span></div>
                                            
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links"
                                class="actions-secondary"<?= /* @noEscape */ strpos($pos, $viewMode . '-secondary') ?
                                $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php endif; ?>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute(
                                        $_product,
                                        $_product->getShortDescription(),
                                        'short_description'
                                    ) ?>
                                    <a href="<?= /* @noEscape */ $_product->getProductUrl() ?>"
                                        title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= $block->escapeHtml('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>

    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>

    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @noEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    require([
      'jquery',
      'jquery/ui'
    ], function($){
        $(document).ready(function() {
            $('.product-item-details').on('click', '.swatch-option', function () {
                var super_attribute = [];
                $(this).parents(".swatch-attribute").each(function() {
                    var id = jQuery(this).parents().attr('class');
                    $("."+id+" .swatch-attribute").each(function() {
                        var id = jQuery(this).attr('data-attribute-id');
                        
                        var value = jQuery(this).attr('data-option-selected');
                        if (value != "") 
                        {
                            super_attribute[id] = value;
                        }
                    });
                    var attr_key = Array();
                    var attr_value = Array();
                    var i = 0;
                    $.each(super_attribute, function( index, value ) {
                        if (value != undefined) {
                            attr_key[i] = index;
                            attr_value[i] = value;
                            i = i + 1;
                        }               
                    });

                    var final = "";
                    for (var i = attr_value.length - 1; i >= 0 ; i--) {
                        final = final+attr_value[i];
                    }
                    var $this = $(this).parents(".product-item-details");

                    jQuery($this).find('.mageants-notify-main #mageants-notify-form-simple > div').each(function() {
                        var id = jQuery(this).attr('id');
                           if (id == final) 
                           {
                            jQuery($this).find('.tocart').hide();
                            $(this).css("display", "block");
                           }
                           else{
                            jQuery($this).find('.tocart').show();
                            $(this).css("display", "none");
                           }
                    });
                });
            });
            $('.notify-button').on('click', function () {
                var customerId = $(this).siblings('.customerId').val();
                var productSku = $(this).siblings('.productSku').val();
                var productName = $(this).siblings('.productName').val();
                var customerEmail = $(this).siblings('.notifyEmail').val();
                var producturl   = $(this).siblings('.producturl').val();
                $.ajax({
                    type: "POST",
                    url: "<?= /* @noEscape */ $notifyBlock->getSaveUrl(); ?>",
                    data: {
                        Id: customerId,
                        Sku:productSku,
                        Name:productName,
                        Email:customerEmail,
                        producturl:producturl
                    },
                    success:  function(data){
                        window.location.reload(true);
                    }
                });    

            });
        });
    }); 
</script>
<style type="text/css">
    .mageants-stock-notification {
        margin: 5px;
        /*float: left;*/
    }
    .product.actions.product-item-actions {
       position: initial;
    }
</style>